Dockerfile
package.json
yarn.lock

This reverts commit 1ec5b771b51e1060c854da580916e56df9475b80.
Running `docker-compose up --build` on develop now results in this:
Running `docker-compose up --build` on this branch seems to work:

Revert "remove duplicate yarn install step"

---

.gitignore
schema.json
src/domain/app/App.tsx
src/domain/customers/CustomerDetailsComponent.stories.tsx
src/domain/customers/CustomerDetailsComponent.tsx
src/domain/customers/CustomerListComponent.stories.tsx
src/domain/customers/CustomerListComponent.tsx
src/domain/customers/CustomerPageContainer.tsx
src/domain/customers/__mocks__/data.ts
src/domain/customers/__mocks__/dummy_customer_data
src/domain/customers/customerList.module.scss
src/domain/customers/queries.ts

- ~~graphql / typescript codegeneration~~
- separate harborlist page into container and representation components
- add storybook story for harborlist
- add dummy customer data for scaffolding
- draft customer list page

VEN-343 | List of current customers

---

.huskyrc.js
package.json
schema.json

Update apollo remote schema and generate typings during git commits to catch errors caused by changed schema.
Possible future development: I'm considering switching apollo's codegenerator to [graphql-code-generator](https://graphql-code-generator.com/) as it seems to be much more flexible.

VEN-361 | Add git commit hook for graphql codegeneration

---

src/assets/styles/main.scss

As far as I understand the fonts are served as files with a .woff extension. I can't seem find the fonts anywhere in hds-core. My current approach is to navigate to https://city-of-helsinki.github.io/helsinki-design-system/storybook and copy the font url from there.
Umm, is this the right approach?

VEN-415 | use fonts from Helsinki Design System

---

schema.json

This PR updates schema.json with `yarn codegen`. This isn't really a bug anymore, since the current schema doesn't break the frontend anymore.

VEN-467 | update schema.json

---

src/domain/harbors/harborDetails/HarborDetails.tsx
src/locales/fi.json

The translations for `harbors.details.serviceMap` was missing. This PR puts it back in.

VEN-464 | add missing translation

---

src/domain/individualApplication/IndividualApplicationPageContainer.tsx

On the single application page, after clicking a customer to an application, it re-fetches the data for the page in question and hides the table of suggested customers.
After linking a customer to a table, you had to refresh the page manually to see the changes.
- From the sidebar, go to `Hakamukset` 
- Click on one of the applications
- From the table, select a customer, then click on `Liitä valittuun`
- Wait until the submission is done, then the table should disappear and the name on `ASIAKASTIEDOT` should show a link to the linked customer's page

VEN-471 | Refetch the query after linking a customer

---

schema.json
src/assets/styles/_colours.scss
src/domain/offer/OfferPageContainer.tsx
src/domain/offer/tableHeader/TableHeader.test.jsx
src/domain/offer/tableHeader/TableHeader.tsx
src/domain/offer/tableHeader/__snapshots__/TableHeader.test.jsx.snap
src/domain/offer/tableHeader/tableHeader.module.scss
src/domain/offer/utils.ts
src/locales/fi.json

Disable pier tabs (filters) for the piers that don't have suitable berths
[VEN-473](https://helsinkisolutionoffice.atlassian.net/browse/VEN-473) Berth details on the Offer page
- Go the applications page `Hakemukset` from the sidebar
- Expand the application's row
- Select one of the choices under `VALITUT SATAMAT`, then it goes to the offer page
- On the offer page: the table has similar filters on the header for piers
- if a [pier has no matched results](https://venepaikka-admin.test.kuva.hel.ninja/offer/QmVydGhBcHBsaWNhdGlvbk5vZGU6NTU=?harbor=42225) the filter is disabled

VEN-473 | Disable table filters for empty results

---

src/domain/offer/OfferPageContainer.tsx

Exact text comparison for pier filters.
When filtering berths by piers, filter “Pier E” includes piers “E” and “E 1”.
[VEN-536](https://helsinkisolutionoffice.atlassian.net/browse/VEN-536): Filter berths by pier filters also by part of the filter
- Go to [one of the offer pages where the harbor has piers which share part of the name like "E" and "E 1"](http://localhost:3000/offer/QmVydGhBcHBsaWNhdGlvbk5vZGU6NDU=?harbor=40897)
- Click on "E" filter; it should show the results for berths only in "E" pier excluding "E 1" berths

VEN-536 | Exact text comparison for piers filters

---

src/assets/styles/_z-index.scss
src/common/dropdown/dropdown.module.scss
src/common/table/table.module.scss

Made table headers stick to the top of the view when scrolling down
Implements [VEN-516: Sticky table headers](https://helsinkisolutionoffice.atlassian.net/browse/VEN-516)
Check the following views that have tables:
* Berths (Venepaikat)
* Single berth
* Applications (Hakemukset)
* Customers (Asiakkaat)

Sticky table headers

---

package.json
src/common/select/Select.tsx
src/common/select/select.module.scss
src/domain/individualApplication/IndividualApplicationPage.tsx
src/domain/individualApplication/IndividualApplicationPageContainer.tsx
src/domain/individualApplication/__generated__/FILTERED_CUSTOMERS.ts
src/domain/individualApplication/customersTableTools/CustomersTableTools.tsx
src/domain/individualApplication/customersTableTools/customersTableTools.module.scss
src/domain/individualApplication/individualApplicationPage.module.scss
src/domain/individualApplication/queries.ts
src/locales/fi.json
yarn.lock

- Add `Select` and `TextField` for searching similar customers on the single application page
- Use the debouncing mechanism for fetching customers while typing  
- Use lazy selector for fetching similar customers to get rid of on unnecessary roundtrip if the application has a customer attached
[VEN-538](https://helsinkisolutionoffice.atlassian.net/browse/VEN-538): Single application page: filters for the suggested customers
- Go to the application page
- Click on one of the applications
- If the application doesn't have a customer, a table with suggested customers would be displayed
- Above the table, there are a search bar and a dropdown menu can be used to search for customers based on their `first name`, `last name`, `email` or `address`.
I left out the pagination to be done in …

VEN-538| Single application page: searching for similar customers

---

src/common/table/Table.tsx
src/common/tableTools/globalSearchTableTools/GlobalSearchTableTools.test.jsx
src/common/tableTools/globalSearchTableTools/GlobalSearchTableTools.tsx
src/common/tableTools/globalSearchTableTools/__snapshots__/GlobalSearchTableTools.test.jsx.snap
src/common/tableTools/globalSearchTableTools/globalSearchTableTools.module.scss
src/domain/harbors/HarborsList.tsx
src/domain/harbors/harborsTableTools/__snapshots__/HarborsTableTools.test.jsx.snap
src/domain/individualHarbor/IndividualHarborPageContainer.tsx
src/domain/individualHarbor/pierSelectHeader/PierSelectHeader.tsx

Adds a search field that performs global filtering of berths in the individual harbor page's table.
Additionally refactors filtering by piers to not use component state.
VEN-579
* Go to a harbor's page.
* Type something in the search text field.
* Only the rows with at least one cell matching the written text should be shown.

VEN-579 | Add global filter to berth table in individual harbor page

---

.huskyrc.js
package.json
yarn.lock

- Use pre-push hook instead of pre-commit hook to run linting and graphql generate
- Update husky

Use pre push hook instead

---

src/domain/customers/CustomerListComponent.tsx
src/domain/customers/CustomerPageContainer.tsx
src/domain/customers/__generated__/CUSTOMERS.ts
src/domain/customers/queries.ts
src/domain/customers/tableTools/TableTools.tsx
src/domain/customers/tableTools/tableTools.module.scss

Add search field for customer list
Search by:
* first name
* last name
* address
* email
[VEN-596](https://helsinkisolutionoffice.atlassian.net/browse/VEN-596) | Customers page: search field for the table
Nada. 👎
Open the customer list
1. Test that data is filtered by first name, last name, address and email correctly
2. Test that the filtered data works with pagination
Sorting works only for the current page. This is also the case for the reference, the single application page.

VEN-596 | Customers page: search field for the table

---

src/common/utils/__tests__/usePagination.test.tsx
src/common/utils/usePagination.ts
src/features/applicationView/ApplicationViewPageContainer.tsx
src/features/customerList/CustomerListPageContainer.tsx

Fixes following issues
- Need to click back three times when opening application that has not been attached to customer
- Need to click back several times after you have used customer search field
- Forces to first page regardless of the url page param on customer list
https://helsinkisolutionoffice.atlassian.net/browse/VEN-683
- Open application that has not been attached to customer, click back, it should take you to applications list
- Go to customer list, search with search box, click back, it should take you to previous screen
- Go to customer list, browse to third page, hit reload in browser, you should stay on third page
Added test case to `usePagination.test.tsx`

VEN-683 | Back button issues

---

src/features/customerList/CustomerListContainer.tsx

* Change fetch policy of `customerListContainer` to `no-cache`
* [VEN-727](https://helsinkisolutionoffice.atlassian.net/browse/VEN-727): FE: data does not get loaded from the API when clicking "Back" button on single customer page
Check that this issue no longer occurs, check the specifics in [this comment](https://helsinkisolutionoffice.atlassian.net/browse/VEN-727?focusedCommentId=14720)
> 1. Go to the list of customers
> 2. Click on any customer to go to their single customer page
> 3. Click "Back" button in the browser
> 4. You will be back on the customers list page, but the data is not loaded

Change fetch policy of customerListContainer to "no-cache"

---

src/features/customerList/customerDetails/CustomerDetails.tsx
src/locales/fi.json

* Show unnamed boats in customer list
* Move CustomerDetails titles to `common.terminology`
* [VEN-737](https://helsinkisolutionoffice.atlassian.net/browse/VEN-737): FE - Customers list page: List unnamed boats
* Verify that unnamed boats are shown as 'Nimetön vene' in expanded row (CustomerDetails)

VEN-737 | Show unnamed boats in customer list

---

src/features/winterStorageAreaList/winterStorageAreaDetails/WinterStorageAreaDetails.tsx
src/features/winterStorageAreaList/winterStorageAreaDetails/__tests__/__snapshots__/WinterStorageAreaDetails.test.tsx.snap

* Remove mooring from winter storage area details
* [VEN-717](https://helsinkisolutionoffice.atlassian.net/browse/VEN-717): FE - Winter storage areas page: Detailed row
* Updated snapshot
* Mooring type should be removed from winter storage area details

VEN-717 | Remove mooring from winter storage area details

---

src/common/checkbox/checkbox.module.scss
src/common/radioButton/RadioButton.tsx
src/common/radioButton/radioButton.module.scss
src/common/select/select.module.scss
src/common/table/Table.tsx

* Increase specifity of selectors of 'Select' and 'Checkbox'
* Use coat-of-arms-blue for RadioButton 
* Verify correct appearance of Select (visible on pricing page, for harbor services)
* Verify correct appearance of Checkbox (visible on customer list page)
* Verify correct appearance of RadioButton (visible on offer page, when selecting customer profile)

Fix appearance of HDS Select, Checkbox and RadioButton outside local env

---

src/@types/__generated__/globalTypes.ts
src/common/customerProfileCard/CustomerProfileCard.stories.tsx
src/common/customerProfileCard/__tests__/CustomerProfileCard.test.tsx
src/common/customerProfileCard/__tests__/__snapshots__/CustomerProfileCard.test.tsx.snap
src/common/organizationCustomerDetails/OrganizationCustomerDetails.tsx
src/common/organizationCustomerDetails/__fixtures__/mockData.ts
src/common/privateCustomerDetails/PrivateCustomerDetails.tsx
src/common/privateCustomerDetails/__fixtures__/mockData.ts
src/features/applicationView/__generated__/INDIVIDUAL_APPLICATION.ts
src/features/applicationView/queries.ts
src/features/applicationView/utils.ts
src/features/customerView/__generated__/INDIVIDUAL_CUSTOMER.ts
src/features/customerView/queries.ts
src/features/customerView/utils.ts
src/locales/fi.json

* Show customer language in application and customer views
* [VEN-540](https://helsinkisolutionoffice.atlassian.net/browse/VEN-540): Add customer's preferred language to customer details
* Updated test data and snapshots
* Check that language is shown on customer profile card in application view
* [URL](http://localhost:3000/applications/QmVydGhBcHBsaWNhdGlvbk5vZGU6NDY=)
* Check that language is shown on customer profile card in customer view
* [URL for private customer](http://localhost:3000/customers/UHJvZmlsZU5vZGU6MDNmZmQ4MjAtOGFlNi00OGUzLWE2ZGItZGFjNTkzMTkzMjQw)
* [URL for organization customer](http://localhost:3000/customers/UHJvZmlsZU5vZGU6MzJlMjIyOTAtNWFjYi00ZTc0LTk2M2UtYmNlZDY3NTllOWU5)
* Check that language is showin in stories for CustomerProfileCard
* [URL for private …

VEN-540 | Show customer language in application and customer views

---

src/@types/__generated__/globalTypes.ts
src/common/applicationDetails/__tests__/ApplicationDetails.test.tsx
src/common/applicationDetails/__tests__/__snapshots__/ApplicationDetails.test.tsx.snap
src/common/customerProfileCard/CustomerProfileCard.stories.tsx
src/common/customerProfileCard/__tests__/CustomerProfileCard.test.tsx
src/common/organizationCustomerDetails/OrganizationCustomerDetails.tsx
src/common/organizationCustomerDetails/__fixtures__/mockData.ts
src/common/organizationCustomerDetails/__tests__/OrganizationCustomerDetails.test.tsx
src/common/organizationCustomerDetails/__tests__/__snapshots__/OrganizationCustomerDetails.test.tsx.snap
src/common/privateCustomerDetails/PrivateCustomerDetails.tsx
src/common/utils/__tests__/translations.test.ts
src/common/utils/translations.ts
src/features/applicationView/ApplicationView.tsx
src/features/applicationView/__generated__/FILTERED_CUSTOMERS.ts
src/features/applicationView/__generated__/INDIVIDUAL_APPLICATION.ts
src/features/applicationView/queries.ts
src/features/applicationView/utils.ts
src/features/customerList/CustomerList.tsx
src/features/customerList/__fixtures__/mockData.ts
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/__mocks__/customersMockResponse.ts
src/features/customerList/customerDetails/CustomerDetails.tsx
src/features/customerList/queries.ts
src/features/customerList/types.ts
src/features/customerList/utils.ts
src/features/customerView/__fixtures__/mockData.ts
src/features/customerView/__generated__/INDIVIDUAL_CUSTOMER.ts
src/features/customerView/queries.ts
src/features/customerView/utils.ts
src/locales/fi.json

Use customerGroup field to determine customer group.
https://helsinkisolutionoffice.atlassian.net/browse/VEN-761
- Unit tests in: `translations.test.ts`
- Several component render tests
- Select "Asiakkaat" from the left menu
- You should see that "Asiakasryhmä" column is populated
- Pro tip: go to the last page and you should see customers with different groups there

VEN-761 | Use customerGroup field to determine customer group

---

src/features/linkApplicationToCustomer/__fixtures__/mockData.ts
src/features/linkApplicationToCustomer/__generated__/FILTERED_CUSTOMERS.ts
src/features/linkApplicationToCustomer/__tests__/__snapshots__/utils.test.ts.snap
src/features/linkApplicationToCustomer/queries.ts
src/features/linkApplicationToCustomer/utils.ts

Because of [VEN-813](https://helsinkisolutionoffice.atlassian.net/browse/VEN-813) we should fetch ws lease `section` instead of `area`. As temporary fix remove the `area` reference to get the query working. We need to fix the whole lease names resolving because the implementation did not take marked ws leases in account (only resolved the unmarked names via area). Will create a separate bug issue from that.
[VEN-813](https://helsinkisolutionoffice.atlassian.net/browse/VEN-813)
- land to `http://localhost:3000/applications/QmVydGhBcHBsaWNhdGlvbk5vZGU6NjY=`
- you should be able to search customer to attach to

Add temporary fix for fetching customer WS leases

---

.gitlab-ci.yml

As the proper URL for the BE is behind a nginx proxy managed
by Kanslia, which is pending necessary config updates, we
could temporarily use the original URL that is provided directly
by Kuva's infra.
Needed to get further testing going by the end users in prod.

Use temporarily direct BE URL

---

src/@types/__generated__/globalTypes.ts
src/common/hooks/__fixtures__/useCreateNewCustomerMockData.ts
src/common/hooks/__tests__/useCreateNewCustomer.test.tsx
src/common/hooks/useCreateNewCustomer.ts
src/common/mutations/__generated__/CREATE_BERTH_SERVICE_PROFILE.ts
src/common/mutations/__generated__/CREATE_NEW_PROFILE.ts
src/common/mutations/createProfile.ts
src/common/utils/translations.ts
src/features/customerView/billingHistoryCard/BillingHistoryCard.tsx
src/features/linkApplicationToCustomer/LinkApplicationToCustomerContainer.tsx
src/locales/fi.json

After sending createProfile mutation the button should also call createBerthServicesProfile, which will also create a profile in the venepaikka backend.
[VEN-834](https://helsinkisolutionoffice.atlassian.net/browse/VEN-834)
`src/common/hooks/__tests__/useCreateNewCustomer.test.tsx `
- Open a single application (either winter storage or harbor) that does not have a connected customer
- Click the "Add new customer" button
- (Network inspector should show a request made to `createProfile` followed by a request to `createBerthServicesProfile` with the input id corresponding to the returned id value from `createProfile`)
- It should be possible to connect the application to the newly created user
`OrderStatus` enum has been extended in the backend, which also required changes to a few files …

VEN-834 | Fix create customer button on the single application page

---

src/common/privateCustomerDetails/__tests__/PrivateCustomerDetails.test.tsx
src/common/privateCustomerDetails/__tests__/__snapshots__/PrivateCustomerDetails.test.tsx.snap
src/common/utils/__tests__/usePagination.test.tsx
src/common/utils/translations.ts
src/features/applicationView/offerCard/__tests__/OfferCard.test.tsx
src/features/customerList/customerDetails/__mocks__/mockData.ts
src/features/customerList/customerDetails/__tests__/CustomerDetails.test.tsx
src/features/customerView/__tests__/CustomerView.test.tsx
src/features/customerView/applicationsCard/ApplicationsCard.test.tsx
src/features/customerView/billingHistoryCard/BillingHistoryCard.tsx
src/features/customerView/boatsCard/__tests__/BoatsCard.test.tsx
src/features/harborView/forms/pierForm/PierForm.stories.tsx
src/features/harborView/forms/pierForm/__tests__/PierForm.test.tsx
src/features/linkApplicationToCustomer/__fixtures__/mockData.ts
src/features/linkApplicationToCustomer/__generated__/FILTERED_CUSTOMERS.ts
src/features/linkApplicationToCustomer/__tests__/__snapshots__/utils.test.ts.snap
src/features/linkApplicationToCustomer/__tests__/utils.test.ts
src/features/linkApplicationToCustomer/queries.ts
src/features/linkApplicationToCustomer/utils.ts
src/features/pricing/editModal/fields/__tests__/AdditionalServicesFields.test.tsx
src/features/pricing/editModal/fields/__tests__/HarborServicesFields.test.tsx
src/features/pricing/editModal/fields/__tests__/__snapshots__/HarborServicesFields.test.tsx.snap
src/features/winterStorageApplicationView/__fixtures__/mockData.ts
src/locales/fi.json

* Show winter storage area names on LinkApplicationToCustomer
* [VEN-824](https://helsinkisolutionoffice.atlassian.net/browse/VEN-824): Link customer list winter storage leases not displayed properly
* Updated test data
* No customers currently have winter storage leases

VEN-824 | Show winter storage area names on LinkApplicationToCustomer

---

src/features/invoiceCard/sendInvoiceForm/SendInvoiceForm.tsx
src/features/invoiceCard/sendInvoiceForm/__tests__/SendInvoiceForm.test.tsx
src/features/invoiceCard/sendInvoiceForm/__tests__/SendInvoiceFormContainer.test.tsx
src/features/invoiceCard/sendInvoiceForm/__tests__/__snapshots__/SendInvoiceForm.test.tsx.snap
src/features/invoiceCard/sendInvoiceForm/__tests__/__snapshots__/SendInvoiceFormContainer.test.tsx.snap
src/features/invoiceCard/sendInvoiceForm/__tests__/utils.test.ts
src/features/invoiceCard/sendInvoiceForm/utils.ts

* Improve date utils
* Set default due date to 14 days from now
* [VEN-852](https://helsinkisolutionoffice.atlassian.net/browse/VEN-852): Creating invoices for unmarked winter storage notices
* Added better tests for date utils
* Updated related snapshots
* Open the invoice sending modal
* Confirm that the default value is 14 days from now

VEN-852 | Improve date utils and set default due date to 14 days from now

---

src/features/applicationList/ApplicationList.tsx
src/features/applicationList/__tests__/ApplicationListContainer.test.tsx
src/features/applicationList/__tests__/__snapshots__/ApplicationList.test.tsx.snap
src/features/applicationList/__tests__/__snapshots__/ApplicationListContainer.test.tsx.snap
src/features/customerList/CustomerList.tsx
src/features/harborList/HarborList.tsx
src/features/pricing/__tests__/__snapshots__/Pricing.test.tsx.snap
src/features/pricing/additionalServicePricing/AdditionalServicePricing.tsx
src/features/pricing/additionalServicePricing/__tests__/__snapshots__/AdditionalServicePricing.test.tsx.snap
src/features/pricing/berthPricing/BerthPricing.tsx
src/features/pricing/berthPricing/__tests__/__snapshots__/BerthPricing.test.tsx.snap
src/features/pricing/harborServicePricing/HarborServicePricing.tsx
src/features/pricing/harborServicePricing/__tests__/__snapshots__/HarborServicePricing.test.tsx.snap
src/features/pricing/winterStoragePricing/WinterStoragePricing.tsx
src/features/pricing/winterStoragePricing/__tests__/__snapshots__/WinterStoragePricing.test.tsx.snap
src/features/unmarkedWsNoticeList/UnmarkedWsNoticeList.tsx
src/features/unmarkedWsNoticeList/__tests__/UnmarkedWsNoticeListContainer.test.tsx
src/features/unmarkedWsNoticeList/__tests__/__snapshots__/UnmarkedWsNoticeList.test.tsx.snap
src/features/unmarkedWsNoticeList/__tests__/__snapshots__/UnmarkedWsNoticeListContainer.test.tsx.snap
src/features/winterStorageApplicationList/WinterStorageApplicationList.tsx
src/features/winterStorageAreaList/WinterStorageAreaList.tsx
src/features/winterStorageAreaList/__tests__/__snapshots__/WinterStorageAreaList.test.tsx.snap

- Sort Harbors List, Winter Storage Areas List, and Customers List tables by name.
- Sort Berth Applications List, Winter Storage Applications List, and Unmarked Winter Storage Notices List by created date.
- Sort the tables on the Pricing page by first columns.
**[VEN-571](https://helsinkisolutionoffice.atlassian.net/browse/VEN-571):** Set default sorting order for tables
- Upadated the relevant snapshots
- The table on the `Venepaikat` page should be sorted by default alphabetically by `Satama`
- The table on `Talvisäilytys` page should be sorted by default alphabetically by `Alue`
- All tables under `Hakemukset` section should be sorted by `PVM` in a descending order
- The table on `Asiakkaat` page should be sorted by default alphabetically by `Nimi`
- The tables on `Hinnasto` page …

VEN-571 | Set default sorting order for all tables

---

src/assets/styles/_form.scss
src/common/confirmationModal/__tests__/ConfirmationModal.test.tsx
src/common/modal/__tests__/Modal.test.tsx
src/features/customerForm/CustomerForm.tsx
src/features/customerList/tableTools/CustomerListTableTools.tsx
src/features/customerView/CustomerViewContainer.tsx
src/features/customerView/billModal/BillModal.tsx
src/features/customerView/billModal/__tests__/BillModal.test.tsx
src/features/harborView/HarborViewContainer.tsx
src/features/harborView/forms/harborForm/harborEditForm.module.scss
src/features/invoiceCard/InvoiceCardContainer.tsx
src/features/pricing/additionalServicePricing/AdditionalServicePricing.tsx
src/features/pricing/berthPricing/BerthPricing.tsx
src/features/pricing/harborServicePricing/HarborServicePricing.tsx
src/features/pricing/winterStoragePricing/WinterStoragePricing.tsx

* Make CustomerForm validate only on submit
* Make all modals close by clicking outside and remove redundant rendering conditions
* [VEN-773](https://helsinkisolutionoffice.atlassian.net/browse/VEN-773): FE - Customer list: Add new customer 
* [VEN-884](https://helsinkisolutionoffice.atlassian.net/browse/VEN-884): Unified modal behavior
* Add / edit customer form should validate when and only when the submit button is clicked, and not when changing customer groups, for example
* All modals should close when clicking the gray backdrop outside them

VEN-773, VEN-884 | Less aggressive customer form validation, unified modal behavior

---

src/common/utils/featureFlags.ts
src/features/applicationView/berthOfferCard/BerthOfferCard.tsx
src/features/invoiceCard/InvoiceCard.tsx
src/features/winterStorageApplicationView/WinterStorageApplicationView.tsx

* Put berth invoicing behind feature flag
* ~Put WS invoicing behind feature flag~
* No implementation exists, so `noop`
* Removed redundant rendering condition from WS application view
* Added TODO comment about WS invoicing
* [VEN-874](https://helsinkisolutionoffice.atlassian.net/browse/VEN-874): Hide "send invoice button" on berth and WS applications
* Berth invoicing should work in local development environment and be hidden in testing/production environments

VEN-874 | Put berth invoicing behind feature flag

---

src/common/applicationDetails/ApplicationDetails.tsx
src/common/harborCard/HarborCard.tsx
src/common/utils/featureFlags.ts
src/features/applicationList/ApplicationList.tsx
src/features/winterStorageApplicationList/WinterStorageApplicationList.tsx

* Put queue features behind feature flag
* [VEN-825](https://helsinkisolutionoffice.atlassian.net/browse/VEN-825): Move placeholder components behind a feature flag
* Queue number and number of items in queue should be hidden in testing environment but visible in local development environment

VEN-825 | Put queue features behind feature flag

---

src/features/offer/queries.ts

If a berth has already been assigned to some application, it should not be offered for other applications.
[VEN-791](https://helsinkisolutionoffice.atlassian.net/browse/VEN-791)
- Go to "Venepaikkahakemukset", select an application that is in state "Odottaa käsittelyä"
- Select a harbor to choose berths from
- The offer table should not contain berths already associated with applications (check and compare with the full applications list for already assigned berths)

VEN-791 | Only show available berths on the offer page

---

src/features/linkApplicationToCustomer/LinkApplicationToCustomerContainer.tsx
src/features/linkApplicationToCustomer/__tests__/LinkApplicationToCustomer.test.tsx
src/features/linkApplicationToCustomer/__tests__/__snapshots__/LinkApplicationToCustomerContainer.test.tsx.snap
src/features/linkApplicationToCustomer/tableTools/CustomersTableTools.tsx
src/features/linkApplicationToCustomer/tableTools/__tests__/CustomersTableTools.test.tsx
src/features/unmarkedWsNoticeView/__tests__/__snapshots__/UnmarkedWsNoticeViewContainer.test.tsx.snap

Disables the create new user button in LinkApplicationToCustomer if users with identical information exist on the backend. Users with same first and last name as well as email count as identical. Additionally sets default filtering to be based on email instead of last name.
[VEN-887](https://helsinkisolutionoffice.atlassian.net/browse/VEN-887)
- Updated relevant tests
- Added tests to `src/features/linkApplicationToCustomer/__tests__/LinkApplicationToCustomer.test.tsx`
- Select an application in state "Odottaa käsittelyä" with no connected user
- If the list of users contains a user with identical information, the create new user button should not appear
- If the list does not contain an identical user, the button should first appear but disappear after creating a new user

VEN-887 | Disable create new user button if users with identical information exist

---

src/app/apolloClient.ts

* This fixes an error handling regression caused by changes related to removing SSN from the application.

Fix: Show GraphQL errors

---

src/features/harborList/HarborList.tsx
src/features/winterStorageAreaList/WinterStorageAreaList.tsx

* Sort select harbor and WS area properties first in desc. order
* [VEN-565](https://helsinkisolutionoffice.atlassian.net/browse/VEN-565): Table number and pier property columns should sort first in descending order
* Place counts and properties on harbor and winter storage area lists should be first sorted in descending order

VEN-565 | Sort select harbor and WS area properties first in desc. order

---

src/app/page/__tests__/__snapshots__/Page.test.tsx.snap
src/common/contactInformationCard/ContactInformationDetails.tsx
src/common/contactInformationCard/__tests__/__snapshots__/ContactInformationCard.test.tsx.snap
src/common/layout/Layout.tsx
src/common/layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/common/layout/layout.module.scss
src/common/pageContent/pageContent.module.scss
src/common/table/table.module.scss
src/features/harborView/__tests__/__snapshots__/HarborView.test.tsx.snap
src/features/pricing/Pricing.tsx
src/features/pricing/__tests__/__snapshots__/Pricing.test.tsx.snap
src/features/pricing/pricing.module.scss
src/features/winterStorageAreaList/winterStorageAreaDetails/__tests__/__snapshots__/WinterStorageAreaDetails.test.tsx.snap
src/features/winterStorageAreaView/__tests__/__snapshots__/WinterStorageAreaViewContainer.test.tsx.snap

* Fit admin UI to a minimum screen width
* Reduce table cell padding
* Make pricing page single column
* Toggleable sidebar
* Disable scrolling if there's nothing to scroll
* Simplify harbor chief information 
* [VEN-920](https://helsinkisolutionoffice.atlassian.net/browse/VEN-920): Fit admin UI to a minimum screen width
* Updated related snapshots (harbor chief)
* Test that the toggleable sidebar works correctly
* No functionality regressions should be caused by this

VEN-920 | Fit admin UI to a minimum screen width

---

src/common/pageContent/pageContent.module.scss
src/features/customerView/invoicingHistoryCard/InvoicingHistoryCard.tsx
src/features/customerView/invoicingHistoryCard/__tests__/__snapshots__/InvoicingHistoryCard.test.tsx.snap
src/features/customerView/invoicingHistoryCard/invoicingHistoryCard.module.scss

* Add period and headers to InvoicingHistoryCard
* Adjust page content behavior on smaller screen sizes
* Card content overflowed on small screen sizes previously, now cards are scaled accordingly
* [VEN-894](https://helsinkisolutionoffice.atlassian.net/browse/VEN-894): FE: Change the due date into right term (sopimuskausi)
* Updated snapshot
* Invoicing history card should now show the period billed in the invoice
* There should be one scrollbar for overflowing page content on smaller screens

VEN-894 | Add period and headers to InvoicingHistoryCard

---

src/common/select/Select.tsx
src/features/pricing/additionalServicePricing/form/AdditionalServicesForm.tsx
src/features/pricing/additionalServicePricing/form/__tests__/__snapshots__/AdditionalServicesForm.test.tsx.snap

- Add `STORAGE_ON_ICE` to additional services
[VEN-814](https://helsinkisolutionoffice.atlassian.net/browse/VEN-814): Pricing page: support "Add New" additional services
[VEN-933](https://helsinkisolutionoffice.atlassian.net/browse/VEN-933): Backend: Add missing product services
- Go to the pricing page
- On the "Lisäpalvelut" table, click on "Lisää uusi" button
- Fill in the "Lisää uusi" modal and submit
- The services should include "Jäissä säilytys" option in the dropdown

 VEN-814 | Add "STORAGE_ON_ICE" to additional services

---

src/@types/__generated__/globalTypes.ts
src/features/applicationList/ApplicationListContainer.tsx
src/features/applicationList/__fixtures__/mockData.ts
src/features/applicationList/__tests__/__snapshots__/ApplicationList.test.tsx.snap
src/features/applicationList/__tests__/__snapshots__/ApplicationListContainer.test.tsx.snap
src/features/applicationList/__tests__/__snapshots__/utils.test.ts.snap
src/features/unmarkedWsNoticeList/UnmarkedWsNoticeListContainer.tsx
src/features/winterStorageApplicationList/WinterStorageApplicationList.tsx
src/features/winterStorageApplicationList/WinterStorageApplicationListContainer.tsx

- Set fetch policy on application lists to `no-cache`
- Fix the link to a single WS application.
[VEN-943](url)https://helsinkisolutionoffice.atlassian.net/browse/VEN-943
Updated relevant tests
- Go to one of the applications list page e.g. Berth Applications List
- Click on one of the applications to go to the single application view
- Go back to the applications list page
- The table displays all the applications
---
- Go to the WS applications
- Click on one of the applications
- It should go to the corresponding application

VEN-943 | Caching issues & Link to WS application

---

src/common/toast/hdsToast.tsx
src/features/offer/Offer.tsx
src/features/offer/OfferContainer.tsx
src/features/offer/__fixtures__/mockData.ts
src/features/offer/__generated__/OFFER.ts
src/features/offer/queries.ts
src/locales/fi.json

Adds a success toast when assigning berths to customers.
[VEN-967](https://helsinkisolutionoffice.atlassian.net/browse/VEN-967)
- Open applications list
- Select an unhandled application
- Go through the application handling flow, assign a suitable berth
- After assigning, the user should be redirected back to the applications list and a success toast with berth and customer information should be shown

VEN-967 | Show success notification when assigning berth

---

src/features/pricing/PricingContainer.tsx

The pricing page should refresh contents without forcing the user to reload the page after changes. Added a refetch to the mutations.
[VEN-814](https://helsinkisolutionoffice.atlassian.net/browse/VEN-814) discussion.

Add refetching to pricing page mutations

---

src/common/toast/__tests__/HDSToastContainer.test.tsx
src/common/toast/hdsToast.tsx

Changes how hdsToast.graphQLErrors handles errors. Together with the backend changes proposed here https://github.com/City-of-Helsinki/berth-reservations/pull/371 we will be able to display meaningful error messages more simply.

Improve hdsToast graphQL error handling

---

src/common/confirmationModal/ConfirmationModal.tsx
src/common/confirmationModal/__tests__/__snapshots__/ConfirmationModal.test.tsx.snap
src/common/confirmationModal/confirmationModal.module.scss
src/common/deleteButton/__tests__/__snapshots__/DeleteButton.test.tsx.snap
src/features/unmarkedWsNoticeDetails/fragments/stickerDetails/StickerDetailsContainer.tsx
src/locales/fi.json

- Change the text on the changing sticker number dialog
- Render `hds-toast` after changing the sticker number successfully
[VEN-984](https://helsinkisolutionoffice.atlassian.net/browse/VEN-984): Add confirmation toast to unmarked WS sticker number change
- Go to [Nostojärjestysilmoitukset page](https://venepaikka-admin.test.kuva.hel.ninja/unmarked-ws-notices)
- Click on `Vaihda numero` button (in the expanded row of an application that has a sticker or on the single application page)
- You would get a confirmation toast if the number changes successfully
Also, the text on the dialog is changed to: 
>Järjestelmä valitsee seuraavan vapaana olevan tarranumeron. Oletko varma että haluat vaihtaa tarranumeron tälle hakemukselle?

VEN-984 | Add confirmation toast after changing the sticker number

---

src/common/wrappingTableCell/WrappingTableCell.tsx
src/common/wrappingTableCell/wrappingTableCell.module.scss
src/features/customerList/CustomerList.tsx
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/__mocks__/customersMockResponse.ts
src/features/customerList/customerDetails/CustomerDetails.tsx
src/features/customerList/customerDetails/__mocks__/mockData.ts
src/features/customerList/customerDetails/__tests__/CustomerDetails.test.tsx
src/features/customerList/queries.ts
src/features/customerList/types.ts
src/features/customerList/utils.ts

1. Make text break in lines when it’s longer than the column.
2. Remove old berths info from customer table rows. Show ONLY current berth.
3. Accordion open. Add a horizontal line under current berth if there is previous berths
* [VEN-989](https://helsinkisolutionoffice.atlassian.net/browse/VEN-989): Fix venepaikat column in customer list table
* Added tests for new horizontal rule feature
* Customer list column contents for berths and applications should now wrap
* Customer list should only show active berths
* Expanded row in customer list should now show a horizontal rule if there are previous berths

VEN-989 | Fix venepaikat column in customer list table

---

src/features/offer/Offer.tsx
src/features/winterStorageAreaView/utils.ts
src/locales/fi.json

* Filter inactive unmarked winter storage leases
* Add message for empty berth list
* [VEN-839](https://helsinkisolutionoffice.atlassian.net/browse/VEN-839): FE - Winter storage list page: filter invalid (refused) leases
* [VEN-968](https://helsinkisolutionoffice.atlassian.net/browse/VEN-968): FE - Message for empty berth list
* Inactive unmarked winter storage leases should no longer be visible in winter storage view
* Berth offer page should show a message in the empty table if there are no suitable berths

VEN-839, VEN-968 | Improve lease and offer tables

---

src/features/customerList/customerDetails/CustomerDetails.tsx

* Previous berths should now be visible in CustomerDetails, and the separator should only appear if there are previous berths
* [VEN-989](https://helsinkisolutionoffice.atlassian.net/browse/VEN-989): Fix venepaikat column in customer list table

VEN-989 | Fix berth separator behavior

---

.eslintrc
browser-tests/customerListView.ts
browser-tests/pages/customers.ts
package.json
src/common/table/Table.tsx
src/common/utils/useBackendSorting.ts
yarn.lock

- Fix the issue that causes the application to go back to the first page after reloading views with backend-paginated tables
- Fix Eslint warnings for e2e tests
[VEN-942](https://helsinkisolutionoffice.atlassian.net/browse/VEN-942): Refreshing paginated tables go back to the first page
https://github.com/City-of-Helsinki/berth-reservations-admin/blob/5528d381c244ee468838578d79133973716ae227/browser-tests/customerListView.ts#L30
- Go to one of the backend paginated tables e.g. Applications List
- Go to the second page
- Refresh the page
- The table should stay and render the second page as expected

VEN-942 | Persist current page after refresh

---

src/common/table/Table.tsx
src/features/unmarkedWsNoticeDetails/UnmarkedWsNoticeDetails.tsx
src/features/unmarkedWsNoticeDetails/__tests__/UnmarkedWsNoticeDetails.test.tsx
src/features/unmarkedWsNoticeDetails/fragments/stickerDetails/StickerDetailsContainer.tsx
src/features/unmarkedWsNoticeList/UnmarkedWsNoticeList.tsx
src/features/unmarkedWsNoticeList/UnmarkedWsNoticeListContainer.tsx
src/features/unmarkedWsNoticeList/printAllStickersButton/PrintAllStickersButton.tsx
src/features/unmarkedWsNoticeList/printAllStickersButton/__generated__/UNMARKED_WINTER_STORAGE_NOTICES_STICKERS.ts
src/features/unmarkedWsNoticeList/printAllStickersButton/queries.ts
src/features/unmarkedWsNoticeList/utils.ts
src/locales/fi.json

Table contents need to be refetched when changing sticker numbers through the unmarked ws notices list details component, as the data to print is taken from the selected row data.
Additionally, prevents data changes from resetting expanded state in Table.
[VEN-1031](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1031)
- Go to unmarked ws list page
- Select a customer with an assigned sticker number
- Expand the row details for that customer and change sticker number
- Print out the sticker for the selected row
- The pdf should contain the newly changed sticker number

VEN-1031 | Fix refreshing of table data when sticker number changes

---

browser-tests/navigateAndView.ts

* Added a simple .exists() check which makes the browser test wait a bit before clicking

Fix browser tests on GitHub CI

---

.github/workflows/browser-tests.yml

Solution for browser test issues. Since windows-latest is the only one with difficult timing issues in browser tests, let's just remove it.
New PR due to GitHub getting stuck waiting on the removed check.

Remove running browser tests on Windows

---

.env
.gitlab-ci.yml
Dockerfile
src/common/utils/featureFlags.ts
src/features/auth/authService.ts

* Add new `REACT_APP_ENV` env var, which corresponds to the runtime environment (development, review, staging, production)
* Enable berth invoicing up to staging (all but `REACT_APP_ENV===production`)
* Fix authService long line lint issue
* [VEN-970](https://helsinkisolutionoffice.atlassian.net/browse/VEN-970): FE - Enable the "Send invoice" button for berth applications
* "Send invoice" for berths should be enabled in development and staging
* "Send invoice" for berths should _not_ be enabled in production

VEN-970 | Enable the "Send invoice" button for berth applications

---

src/@types/__generated__/globalTypes.ts
src/common/utils/featureFlags.ts
src/common/utils/translations.ts
src/features/applicationList/ApplicationListContainer.tsx
src/features/createAdditionalInvoice/CreateAdditionalInvoiceContainer.tsx
src/features/createAdditionalInvoice/LeaseInformation.tsx
src/features/customerView/__fixtures__/mockData.ts
src/features/customerView/__generated__/INDIVIDUAL_CUSTOMER.ts
src/features/customerView/invoicingHistoryCard/InvoicingHistoryCard.tsx
src/features/customerView/openInvoicesCard/OpenInvoicesCard.tsx
src/features/customerView/queries.ts
src/features/customerView/types.ts
src/features/customerView/utils.ts
src/features/invoiceCard/sendInvoiceForm/SendInvoiceFormContainer.tsx
src/features/invoiceCard/sendInvoiceForm/__tests__/SendInvoiceFormContainer.test.tsx
src/features/unmarkedWsNoticeList/UnmarkedWsNoticeListContainer.tsx
src/locales/fi.json

- Show different title for additional product order
- Send profile token on approve order
https://helsinkisolutionoffice.atlassian.net/browse/VEN-1017
Go to:
http://localhost:3000/customers/UHJvZmlsZU5vZGU6MTBiZGYyYzUtYzk0NS00MGNlLTk0M2QtZjU4YTA3MDU4YzE1
You should see different titles for AP invoices.

VEN-1017 | Additional invoice adjustments

---

browser-tests/navigateAndView.ts

* Temporarily commented out pricing browser tests while waiting for a fix, so that other features are unblocked

Temporarily disable pricing browser tests

---

src/@types/__generated__/globalTypes.ts
src/common/table/Table.tsx
src/features/harborView/forms/pierForm/PierCreateForm.tsx
src/features/pricing/__tests__/__snapshots__/Pricing.test.tsx.snap
src/features/pricing/berthPricing/BerthPricing.tsx
src/features/pricing/berthPricing/__tests__/__snapshots__/BerthPricing.test.tsx.snap
src/features/pricing/berthPricing/berthPricing.module.scss
src/features/pricing/harborTiers/HarborTiers.tsx

- Improve the styles of the pricing page
- Reenable `createPier` after updating the schema types
VEN-986: Update pricing page for new berth prices

VEN-986 | Pricing page improvements

---

package.json

Increate the server init delay to 90 seconds
Failing browser tests
Only the first browser test keeps failing, so I am suspecting that the issue has to do with the server not being ready.

Increase server init delay time

---

src/features/applicationView/berthOfferCard/BerthOfferCard.tsx
src/features/invoiceCard/InvoiceCard.tsx
src/features/invoiceCard/OrderSection.tsx
src/features/invoiceCard/__tests__/InvoiceCard.test.tsx
src/features/invoiceCard/__tests__/__snapshots__/InvoiceCard.test.tsx.snap
src/features/unmarkedWsNoticeView/UnmarkedWsNoticeView.tsx

* Disable 'edit additional services' button if invoice is sent
* [VEN-1027](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1027): Invoice 'edit additional services' button should be inactive if invoice is sent

VEN-1027 | Disable 'edit additional services' button if invoice is sent

---

src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/__mocks__/customersMockResponse.ts
src/features/customerList/customerDetails/CustomerDetails.tsx
src/features/customerList/customerDetails/__mocks__/mockData.ts
src/features/customerList/customerDetails/__tests__/CustomerDetails.test.tsx
src/features/customerList/queries.ts
src/features/customerList/types.ts
src/features/customerList/utils.ts
src/locales/fi.json

* Change logic for customer details to show inactive but offered berths as active
* Change horizontal rule to "AIEMMAT VENEPAIKAT" title
* [VEN-1032](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1032): Customer list accordion open shows unpaid invoice as history
* Updated test selector
* We could look into using React Testing Library to make more sane selectors
* [This customer](http://localhost:3000/customers/UHJvZmlsZU5vZGU6NGRmNmQzMGMtYWU4Mi00ZWNkLTkyNGEtYjE0MjBiMDIwZTRm) has an offered berth that has not yet been paid
* It should be visible under "VENEPAIKAT" and not "AIEMMAT VENEPAIKAT" on the customer list
* "AIEMMAT VENEPAIKAT" should be visible for some other customers, check the last page on default sorting

VEN-1032 | Fix customer list accordion open shows unpaid invoice as history

---

src/features/recurringInvoices/recurringInvoicesForm/RecurringInvoicesForm.tsx
src/features/recurringInvoices/recurringInvoicesForm/__tests__/__snapshots__/RecurringInvoicesForm.test.tsx.snap

- Rename the `id` of `dueDate` on the recurring invoices page
The user is not able to change the due date on the recurring invoices page

Fix recurring invoices due date selection

---

src/common/berthDetails/BerthDetails.tsx
src/common/berthDetails/__tests__/__snapshots__/BerthDetails.test.tsx.snap
src/features/applicationList/ApplicationList.tsx
src/features/applicationList/__tests__/__snapshots__/ApplicationList.test.tsx.snap
src/features/customerList/CustomerList.tsx
src/features/recurringInvoices/RecurringInvoices.tsx
src/locales/fi.json

* Add empty name placeholders for applications, customers and recurring invoices
* [VEN-1058](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1058): customers without name can't be accessed

VEN-1058 | Add empty name placeholders for applications, customers and recurring invoices

---

src/features/customerView/__fixtures__/mockData.ts
src/features/customerView/__generated__/INDIVIDUAL_CUSTOMER.ts
src/features/customerView/invoiceModal/InvoiceModal.tsx
src/features/customerView/openInvoicesCard/OpenInvoicesCard.tsx
src/features/customerView/queries.ts
src/features/customerView/types.ts
src/features/customerView/utils.ts
src/locales/fi.json

* Add the `paidAt` detail to the invoice modal when the order has been paid
https://github.com/City-of-Helsinki/berth-reservations/pull/427
1. Go to a customer with invoices: http://localhost:3000/customers/UHJvZmlsZU5vZGU6YTVmZjEzZGEtNDJmMS00ODdkLWFlNzMtMWJkOGNlNjZhYzU2
2. On the `Laskuhistoria` section, click the invoice detail for a paid order, it will open the modal and show a new row: `Maksettu: 19.11.2020`
3. If you open an invoice which hasn't been paid, it won't show it

Add paidAt to invoice detail on CustomerView

---

src/features/customerView/__fixtures__/mockData.ts
src/features/customerView/__generated__/INDIVIDUAL_CUSTOMER.ts
src/features/customerView/leasesCard/LeasesCard.test.tsx
src/features/customerView/openInvoicesCard/OpenInvoicesCard.tsx
src/features/customerView/openInvoicesCard/__tests__/OpenInvoicesCard.test.tsx
src/features/customerView/queries.ts
src/features/customerView/types.ts
src/features/customerView/utils.ts

Adds contract details to open invoices.
[VEN-1061](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1061)
Updated relevant tests.
- Open a customer's page that has open invoices. For example http://localhost:3000/customers/UHJvZmlsZU5vZGU6YTVmZjEzZGEtNDJmMS00ODdkLWFlNzMtMWJkOGNlNjZhYzU2 in staging.
- The open invoices should have contract info displayed.

VEN-1061 | Add contract details to OpenInvoicesCard

---

src/common/hooks/useCreateNewCustomer.ts
src/features/linkApplicationToCustomer/LinkApplicationToCustomerContainer.tsx

* Refetch customer queries when new customer is created
* [VEN-1029](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1029): 'Create customer' button doesn’t do anything until page is refreshed
* No way to currently test this automatically
* When creating a customer profile for a new customer, the list should now display as loading and update correctly.

VEN-1029 | Refetch customer queries when new customer is created

---

src/common/select/Select.tsx
src/features/applicationView/berthOfferCard/__tests__/__snapshots__/BerthOfferCard.test.tsx.snap
src/features/invoiceCard/InvoiceCardContainer.tsx
src/features/invoiceCard/invoiceActions/InvoiceActions.tsx
src/features/invoiceCard/invoiceActions/__tests__/__snapshots__/InvoiceActions.test.tsx.snap
src/locales/fi.json

- Add placeholder text to InvoiceActions component
- Fix the conditions of disabling invoice actions
(VEN-1082)[https://helsinkisolutionoffice.atlassian.net/browse/VEN-1082]:  Fix Invoice Actions Disabling Conditions
- The actions of the invoices that have statuses other than `waiting` or `error` will be disabled

VEN-1082 | Fix Invoice Actions Disabling Conditions

---

src/@types/__generated__/globalTypes.ts
src/common/tableTools/applicationTableTools/__tests__/__snapshots__/ApplicationTableTools.test.tsx.snap
src/common/utils/constants.ts
src/features/applicationList/__tests__/__snapshots__/ApplicationList.test.tsx.snap
src/features/applicationList/__tests__/__snapshots__/ApplicationListContainer.test.tsx.snap
src/features/customerView/invoicingHistoryCard/InvoicingHistoryCard.tsx
src/features/invoiceCard/InvoiceCard.tsx
src/features/invoiceCard/__tests__/InvoiceCard.test.tsx
src/features/invoiceCard/__tests__/__snapshots__/InvoiceCard.test.tsx.snap
src/features/unmarkedWsNoticeList/__tests__/__snapshots__/UnmarkedWsNoticeList.test.tsx.snap
src/features/unmarkedWsNoticeList/__tests__/__snapshots__/UnmarkedWsNoticeListContainer.test.tsx.snap
src/locales/fi.json

- Add ORDER_STATUS to constants file
- Replace status the `util` function with constant values & use translated text in the invoice history card
- Add status label to the invoice card header
[VEN-1097](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1097): Admin UI. Show if the customer has refused an offer or terminated a contract
- From the applications list, go to a single application 
- The order status should be displayed on the `Tarjous` card

VEN-1097 | Add Invoice Status to Invoice Card Header

---

src/common/utils/constants.ts
src/features/customerView/__tests__/__snapshots__/utils.test.ts.snap
src/features/customerView/__tests__/utils.test.ts
src/features/customerView/leasesCard/BerthLeasesCard.tsx
src/features/customerView/leasesCard/LeasesCard.test.tsx
src/features/customerView/leasesCard/LeasesCard.tsx
src/features/customerView/leasesCard/WinterStorageLeasesCard.tsx
src/features/customerView/leasesCard/__snapshots__/LeasesCard.test.tsx.snap
src/features/customerView/leasesCard/leasesCard.module.scss
src/features/customerView/types.ts
src/features/customerView/utils.ts
src/locales/fi.json

- Add a status label to the card 
- Hide the terminating button for unsupported statuses 
[VEN-1213](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1213) Terminate lease doesn't work if the invoice is in error state

VEN-1213 | Leases Card Improvements

---

src/common/table/Table.tsx
src/features/offer/Offer.tsx
src/features/offer/OfferContainer.tsx
src/features/offer/offer.module.scss
src/features/offer/utils.ts
src/features/pricing/berthPricing/BerthPricing.tsx
src/locales/fi.json

- Expose a prop to control cell props & highlight the cells of unsuitable lengths
- Add a confirmation modal to unsuitable berths
[VEN-1240](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1240): Application handling: show all the free berths even when they are shorter than the customer boat
- [VEN-1251](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1251): `piers` query: don't filter the berths based on the length when `forApplication` param is passed
- Go to a single applications page
- Start the process of handling an application
- On the offer page, you should be able to see berths shorter than the applicant's boat
- Short berths should be highlighted in red and a confirmation modal will be shown when selecting a short berth

VEN-1240 | Show all berths regardless of the suitable boat length 

---

src/common/utils/featureFlags.ts
src/features/applicationView/berthOfferCard/BerthOfferCard.tsx

- Remove berthInvoicingFeatureFlag
- [VEN-1260](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1260): Enable berth invoicing in production
- The issue raised by Joonas [in Slack](https://helsinkicity.slack.com/archives/CBA1QHTHN/p1617191906070600)
- In **production**, the offer card should show the `Lähetä tarjous` button

VEN-1260 | Enable Berth Invoicing in Production

---

src/features/offer/Offer.tsx
src/features/offer/__fixtures__/mockData.ts
src/features/offer/__generated__/OFFER.ts
src/features/offer/__generated__/OFFER_WITHOUT_APPLICATION_HARBOR.ts
src/features/offer/__generated__/OfferPiers.ts
src/features/offer/__tests__/__snapshots__/utils.test.ts.snap
src/features/offer/fragments.ts
src/features/offer/types.ts
src/features/offer/utils.ts

* Disable offer button for inactive berths
* [VEN-1264](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1264): Don't show "Not in use" berths for admin during application handling
* Updated mock data and snapshot
* Mark a berth as inactive
* "Valitse" button for that berth should be disabled

VEN-1264 | Disable offer button for inactive berths

---

src/@types/__generated__/globalTypes.ts
src/common/utils/constants.ts
src/common/utils/translations.ts
src/features/applicationView/berthOfferCard/__fixtures__/mockData.ts
src/features/applicationView/berthOfferCard/__tests__/__snapshots__/utils.test.ts.snap
src/features/customerView/CustomerViewContainer.tsx
src/features/customerView/__fixtures__/mockData.ts
src/features/customerView/invoiceModal/__tests__/__snapshots__/InvoiceModal.test.tsx.snap
src/features/customerView/invoicingHistoryCard/__tests__/__snapshots__/InvoicingHistoryCard.test.tsx.snap
src/features/invoiceCard/InvoiceCardContainer.tsx
src/features/invoiceCard/__tests__/InvoiceCard.test.tsx
src/features/invoiceCard/__tests__/__snapshots__/InvoiceCard.test.tsx.snap
src/locales/fi.json

- Replace the depricated WAITING status with OFFERED and DRAFTED statuses 
[VEN-1257](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1257)
- Updated failing snapshots 
- Everything for handling applications should work as expected 
- New statuses have been introduced
- Luotu: before the offer is sent
- Tarjottu: after the offer is sent

VEN-1257 | Support DRAFTED & OFFERED order statuses

---

src/common/modal/modal.module.scss
src/common/utils/constants.ts
src/features/berthOffer/BerthSwitchOfferContainer.tsx
src/features/berthOffer/components/BerthOfferTable.tsx
src/features/customerView/switchBerth/SwitchBerthModal.tsx
src/features/customerView/switchBerth/switchBerthModal.module.scss

* Show BerthOfferTable as loading if isSubmitting
* Adjust modal overflows
* Detected this while preparing for demo
* Fix offer status labels
* Return after creating berth switch offer via SelectBerthLease
* [VEN-1206](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1206): FE - Send a berth switch offer
* When submitting offers, the table should change state into loading
* Both undersized and oversized modals should now behave correctly
* Offer status labels should now be correct
* Creating a switch offer where the lease has to be manually selected should now work correctly

VEN-1206 | Fixes to berth switch application handling

---

src/common/applicationDetails/__tests__/__snapshots__/ApplicationDetails.test.tsx.snap
src/features/berthOffer/BerthSwitchOfferContainer.tsx
src/features/customerView/applicationsCard/__snapshots__/ApplicationsCard.test.tsx.snap
src/locales/fi.json

* Adjust wording on ApplicationDetails
* Show success toast after succesfully creating an offer using SelectBerthLease
* [VEN-1132](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1132): Change terminology in application view offer card
* [VEN-1239](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1239): Add dialog for exchange application handling when the system can't match pier/berth data
* Create an offer for a customer with an existing lease and a switch application that has an incorrect current berth
* There should be a success toast after creating the offer

VEN-1132, VEN-1239 | Show success toast after SelectBerthLease, adjust wording

---

src/features/pricing/additionalServicePricing/form/AdditionalServicesForm.tsx
src/features/pricing/additionalServicePricing/form/__tests__/__snapshots__/AdditionalServicesForm.test.tsx.snap

* Disable changing time period for existing additional invoice pricing row
* [VEN-1038](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1038): Additional invoice edit error not showing
* Updated snapshots
* Changing the time period for an existing additional invoice pricing row should be disabled

VEN-1038 | Disable changing time period for existing additional invoice pricing row

---

src/common/applicationHeader/ApplicationHeader.tsx
src/common/applicationHeader/__tests__/__snapshots__/ApplicationHeader.test.tsx.snap
src/features/applicationView/__tests__/__snapshots__/ApplicationView.test.tsx.snap
src/features/unmarkedWsNoticeView/UnmarkedWsNoticeView.tsx
src/locales/fi.json

* Change "delete notice" to "delete application" for applications
* [VEN-1235](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1235): Wrong label in "delete application" button
* Updated snapshots
* Delete button on application view should now say "Delete application"
* Delete button on nmarked winter storage notice view should still say "Delete notice"

VEN-1235 | Change "delete notice" to "delete application" for applications

---

src/common/tableTools/applicationTableTools/ApplicationTableTools.tsx
src/common/utils/constants.ts

* Sorted application status filters to represent the application flow better
* [VEN-1115](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1115): Filter dropdown items in unlogical order - Application list view
* The application status filters should now be in a logical order

VEN-1115 | Sort application status filters

---

src/@types/__generated__/globalTypes.ts
src/features/invoiceCard/InvoiceCardContainer.tsx
src/features/invoiceCard/refundOrder/RefundOrder.tsx
src/features/invoiceCard/refundOrder/RefundOrderContainer.tsx
src/features/invoiceCard/refundOrder/__generated__/REFUND_ORDER.ts
src/features/invoiceCard/refundOrder/__tests__/RefundOrderContainer.test.tsx
src/features/invoiceCard/refundOrder/mutations.ts
src/features/invoiceCard/refundOrder/refundOrder.module.scss
src/locales/fi.json

[VEN-1160](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1160): Admin can refund full invoice amount to the customer
https://github.com/City-of-Helsinki/berth-reservations-admin/blob/c07156f5856575149c861ec52a559a629f65c81e/src/features/invoiceCard/refundOrder/__tests__/RefundOrderContainer.test.tsx
- After handling an application and sending an offer, the user should sign and pay the order
- From the single application view, click on the `Laskun muokkaus` dropdown and select `Maksunpalautus` 
- Submit the refund order 
NOTE: For technical reasons, the order status remains `PAID` for about five minutes after submitting the refund order, so only by refreshing the page after a while the admin would see the `REFUNDED` status.

VEN-1160 | Refund Orders

---

src/features/applicationView/__fixtures__/mockData.ts
src/features/applicationView/__generated__/INDIVIDUAL_APPLICATION.ts
src/features/applicationView/queries.ts
src/features/applicationView/utils.ts

- Replace the Pier id with its identifier on the Lease Details card on the single application page
- [VEN-1332](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1332): Hakemus card is showing pier id instead of the "identifier"
- Go to a single switch application page
- On the Hakemus card, the value of "Satama ja paikka" should show the pier identifier e.g. "A" instead of the id

VEN-1332 |  Replace Pier id with its identifier on the Lease Details card

---

src/common/tableTools/globalSearchTableTools/globalSearchTableTools.module.scss
src/features/harborView/HarborViewTable.tsx
src/features/harborView/customerName/CustomerName.tsx
src/features/winterStorageAreaView/UnmarkedWinterStorageLeaseTable.tsx
src/features/winterStorageAreaView/WinterStoragePlaceTable.tsx
src/features/winterStorageAreaView/__fixtures__/mockData.ts
src/features/winterStorageAreaView/__generated__/INDIVIDUAL_WINTER_STORAGE_AREA.ts
src/features/winterStorageAreaView/__tests__/__snapshots__/WinterStorageAreaViewContainer.test.tsx.snap
src/features/winterStorageAreaView/__tests__/__snapshots__/utils.test.ts.snap
src/features/winterStorageAreaView/queries.ts
src/features/winterStorageAreaView/types.ts
src/features/winterStorageAreaView/utils.ts
src/locales/fi.json

- Change the query to retrieve customer info from the lease rather than the application
- Let `CustomerInfo` component handles fetching customer's name
[VEN-1334](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1334): Imported winter storage leases not shown in the winter storage area
- Updated related tests
- Go to the [page](https://venepaikka-admin.test.kuva.hel.ninja/winter-storage-areas/V2ludGVyU3RvcmFnZUFyZWFOb2RlOjlkNTc3Yzk5LTYzZjMtNDIzNC04MTM4LWY3MGE0Zjg2ODRmMg==) mentioned in the ticket 
- The place number `1` should show the leaseholder name
- Customers' names on both Marked & Unmarked Winter Storage Areas are now fetched separately, therefore you'll notice a loading indicator in the corresponding table cells first

VEN-1334 | Winter Storage Areas: Display active leases that have no applications attached

---

src/common/utils/constants.ts
src/features/customerView/invoiceModal/InvoiceModal.tsx
src/features/customerView/invoiceModal/__tests__/__snapshots__/InvoiceModal.test.tsx.snap
src/features/customerView/invoiceModal/invoiceModal.module.scss

- Change the order of order-status filter options
- Make the text of the total amount bold in the order details modal
- On the single customer, the filter dropdown above the invoices table now follows a logical order
- Clicking on one of the invoices, the total amount text is bolded

VEN-1242 | Change the order of order-status filter options

---

.env
.github/workflows/review.yml
.github/workflows/staging.yml
README.md
src/features/auth/__snapshots__/authService.test.js.snap

Switch the staging and review environments to use Kanslia's test Tunnistamo and HKI Profile to be able to test Suomi.fi strong authentication. Requires the same changes to [the backend](https://github.com/City-of-Helsinki/berth-reservations/pull/618) and to [the federation gateway](https://github.com/City-of-Helsinki/berth-federation-gateway/pull/39).
**[VEN-1401](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1401)** 
It is not possible to fully test this before merging, but most parts can be tested locally. 
Currently it is not possible to get PR environments' authentication to actually work with Kanslia's Tunnistamo, but those envs are not working at the moment anyway, so we switch them to Kanslia's Tunnistamo to prevent confusion in the future.

VEN-1401 | Use Kanslia's test Tunnistamo and HKI Profile

---

src/features/applicationView/__fixtures__/mockData.ts
src/features/applicationView/__generated__/INDIVIDUAL_APPLICATION.ts
src/features/applicationView/queries.ts

VEN-1454. Apollo threw an error when the 2nd level node of individual application query did not contain an id. An cache issue which is described here: https://www.apollographql.com/docs/react/caching/cache-configuration/#default-identifiers

Fix the Apollo issue of the create berth switch offer

---

src/common/table/Table.tsx
src/common/table/table.module.scss
src/features/applicationList/__tests__/__snapshots__/ApplicationList.test.tsx.snap
src/features/applicationList/__tests__/__snapshots__/ApplicationListContainer.test.tsx.snap
src/features/customerList/CustomerList.tsx
src/features/customerView/__tests__/__snapshots__/CustomerView.test.tsx.snap
src/features/harborView/__tests__/__snapshots__/HarborView.test.tsx.snap
src/features/linkApplicationToCustomer/__tests__/__snapshots__/LinkApplicationToCustomer.test.tsx.snap
src/features/linkApplicationToCustomer/__tests__/__snapshots__/LinkApplicationToCustomerContainer.test.tsx.snap
src/features/unmarkedWsNoticeList/__tests__/__snapshots__/UnmarkedWsNoticeList.test.tsx.snap
src/features/unmarkedWsNoticeList/__tests__/__snapshots__/UnmarkedWsNoticeListContainer.test.tsx.snap
src/features/unmarkedWsNoticeView/__tests__/__snapshots__/UnmarkedWsNoticeViewContainer.test.tsx.snap
src/features/winterStorageAreaList/__tests__/__snapshots__/WinterStorageAreaList.test.tsx.snap
src/features/winterStorageAreaView/__tests__/__snapshots__/WinterStorageAreaViewContainer.test.tsx.snap

It was very hard for me to get clear picture how the headers were handled in the function that returns` tableColumns` (mostly because I haven't used react table that much). I think I found a solution that still works but is much more readable.
In this solution "extra" headers are not part of the columns structure that react table uses but rather manually rendered in the sticky headers div. `tableState` (`TableInstance<D>`) is passed to the `renderMainHeader` render prop as a parameter.
Simplified `tableColumns` calculation:
```
const tableColumns = React.useMemo(() => {
return [
...(canSelectRows ? [selectorCol] : []),
...(canSelectOneRow ? [radioSelectorCol] : []),
...columns,
...(renderSubComponent ? [expanderCol] : []),
];
}, [canSelectRows, selectorCol, canSelectOneRow, …
```

Refactor how headers are handle in Table component

---

src/features/customerList/CustomerList.tsx
src/features/customerList/CustomerListContainer.tsx
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/queries.ts
src/features/customerList/tableTools/__tests__/CustomerListTableTools.test.tsx
src/locales/fi.json

Adds sticker number and registration number filters into customer list dropdown filters.
[VEN-1438](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1438)
[VEN-1439](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1439)

VEN-1438, VEN-1439 | Add new dropdown filters

---

src/common/utils/usePagination.ts
src/features/customerList/CustomerListContainer.tsx
src/features/customerList/customerListTableFilters/CustomerListTableFilters.tsx
src/features/customerList/customerListTableFilters/CustomerListTableFiltersForm.tsx

Fixes issues with pagination:
* Changing page reset filters
* Removing all filters doesn't clear persisted filters from session storage
Queries on customers page can be forced through by typing for instance `lind` in the surname filter box.

VEN-1431 | Fix pagination in customer list page

---

src/common/utils/useBackendSorting.ts

A previous change accidentally transformed a callback into a "factory" which resulted in the callback not being called.
https://github.com/City-of-Helsinki/berth-reservations-admin/commit/75cd28b745ab6bba69f63c5d66bd440b275d79d4#diff-77f21d0fb28d2e1a5a0460d95151caf6444585f49d6042306ff6edb6d539f323R12

Fix broken sort by

---

src/common/utils/useTableExport.ts

API renamed `profile_token` field to `profileToken` to be consistent with the GraphQL side.
Refs VEN-1443

Fix customer xlsx export 

---

src/features/customerList/__generated__/ALL_CUSTOMERS.ts
src/features/customerList/queries.ts

Hooks up new filters with the customer exporter.
Now only users matching the filters should be included in the generated excel.
[VEN-1443](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1443)

VEN-1443 | Fix customer export filtering

---

src/features/applicationView/ApplicationViewContainer.tsx
src/features/unmarkedWsNoticeView/UnmarkedWsNoticeViewContainer.tsx
src/features/winterStorageApplicationView/WinterStorageApplicationViewContainer.tsx

Fixes two issues with customer linking in application view.
**Fix application refresh after customer linking**  
After linking a customer, the data in the view wasn't automatically updated.
The data was supposed to be updated with `refetchQueries`. However, because one refetched query had `no-cache` fetch policy, the refetch failed. A new query was never sent to the server.
The `no-cache` policy was added in conjunction with the export functionality. I wasn't able to determine the intention behind setting the policy to `no-cache` so I tested the export functionality with fetch policy set as `no-cache`. I couldn't spot any issues. But I am bit hesitant because I would have liked to get a hunch about the reasoning behind the fetch policy.
**Fix customer unlinking**  
While debugging for the …

VEN-957, VEN-1498 | Fix customer linking in application view

---

src/@types/__generated__/globalTypes.ts
src/features/harborView/HarborViewTable.tsx
src/features/harborView/__fixtures__/mockData.ts
src/features/harborView/__generated__/INDIVIDUAL_HARBOR.ts
src/features/harborView/__tests__/HarborView.test.tsx
src/features/harborView/__tests__/__snapshots__/HarborView.test.tsx.snap
src/features/harborView/__tests__/__snapshots__/utils.test.ts.snap
src/features/harborView/customerName/CustomerName.tsx
src/features/harborView/queries.ts
src/features/harborView/types.ts
src/features/harborView/utils.ts

Adds previous lease customer name to the Customer column to the Harbors table view
If there is an active lease -> show current customer name as link
If there is no active lease but previous lease exists -> show previous customer name as greyed out text
Otherwise cell is empty

VEN-1501: Adds previous lease to the admin UI

---

src/features/harborView/HarborView.tsx
src/features/harborView/HarborViewContainer.tsx
src/features/harborView/HarborViewTable.tsx
src/features/harborView/__generated__/INDIVIDUAL_HARBOR.ts
src/features/harborView/__tests__/__snapshots__/HarborView.test.tsx.snap
src/features/harborView/harborViewTableFilters/HarborViewTableFilters.tsx
src/features/harborView/harborViewTableFilters/HarborViewTableFiltersForm.tsx
src/features/harborView/harborViewTableFilters/harborViewTableFilters.module.scss
src/features/harborView/harborViewTableFilters/types.ts
src/features/harborView/queries.ts
src/locales/fi.json

VEN-1482 VEN-1488. 
NOTE: This pull request first needs changes from the Berth Reservations API: https://github.com/City-of-Helsinki/berth-reservations/pull/668
Can be tested with `Merihaan venesatama (Hakaniemenranta 30)` or some else which have inactive berths.
1 page of active berths:
5 pages of all berths (inactive included):

Add a show inactive berths filter to the harbor view

---

src/features/applicationView/__tests__/__snapshots__/utils.test.ts.snap
src/features/customerForm/CustomerForm.tsx
src/features/customerForm/__fixtures__/mockData.ts
src/features/customerForm/__generated__/CUSTOMER_FORM.ts
src/features/customerForm/__tests__/__snapshots__/CustomerForm.test.tsx.snap
src/features/customerForm/__tests__/__snapshots__/EditCustomerFormContainer.test.tsx.snap
src/features/customerForm/__tests__/__snapshots__/utils.test.ts.snap
src/features/customerForm/queries.ts
src/features/customerForm/types.ts
src/features/customerForm/utils.ts
src/features/customerList/CustomerListContainer.tsx
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/queries.ts
src/features/customerList/tableTools/CustomerListTableTools.tsx
src/features/customerList/useCustomersQuery.ts
src/features/customerView/utils.ts
src/features/unmarkedWsNoticeView/__tests__/__snapshots__/UnmarkedWsNoticeView.test.tsx.snap
src/locales/fi.json

- Adds invoicing status to customer details customer card
- Allows invoicing type to be changed between PAPER_INVOICE and ONLINE_PAYMENT on customer edit form
- Allows customer profiles to be filtered by invoicingTypes PAPER_INVOICE and ONLINE_PAYMENT

VEN-1169 | Allow customer invoicing type to be controlled and filtered

---

src/features/winterStorageAreaView/forms/placeForm/PlaceEditForm.tsx
src/features/winterStorageAreaView/forms/placeForm/PlaceForm.tsx
src/features/winterStorageAreaView/forms/placeForm/__tests__/PlaceEditForm.test.tsx

This fixes the "Place is in use" toggle in winter storage place edit, by including the `isActive` value in the update query.
Ven-1527
The highlighted toggle in the screenshot should change and place in the list and if unchecked, customer column in the list will display red "Ei käytössä" box.

Ven-1527: Add isActive to winterStorage place update

---

src/features/customerView/leasesCard/WinterStorageLeasesCard.tsx

Section and place were missing from the Winterstorage card on customer profile, this will add them there.
ven-1528

Add sectionIdentifier and placeNumber to address on winterstorage card

---

src/features/customerList/CustomerListContainer.tsx
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/queries.ts
src/features/customerList/useCustomersQuery.ts
src/locales/fi.json

Seems the customer filter doesn't timeout as much as before. Queries are slow, but nevertheless filtering does seem to work without `harbourId` limitation too (in test). So this removes the limitation, but informs users about the slowness of the queries. Whenever the queries start working faster, the notification can be removed (and other related tickets finally resolved).
Also, there was a bug how the `invoicingTypes` was handled on the query, which most of the time resulted on empty results, this also fixes that.
VEN-1537
https://helsinkisolutionoffice.atlassian.net/browse/VEN-1480
https://helsinkisolutionoffice.atlassian.net/browse/HP-1317
https://helsinkisolutionoffice.atlassian.net/browse/VEN-1481

Ven-1537 Update customer filter

---

src/features/customerList/CustomerListContainer.tsx

Small fix to clear the input field after selecting invoicing type. Currently the selection value is converted to the text in the input field after selecting invoicing type as filter, and then something else - this results to the string, for example, "ONLINE_PAYMENT" staying in the field. This fixes that by clearing the field with useEffect hook if changing from invoicing type.
ven-1543

VEN-1543 Clear customer list search field after invoicing type selection

---

src/features/customerList/CustomerListContainer.tsx
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/queries.ts
src/features/customerList/tableTools/CustomerListTableTools.tsx
src/features/customerList/tableTools/customerListTableTools.module.scss
src/features/customerList/useCustomersQuery.ts
src/locales/fi.json

This allows filtering searches by both sticker number and season combination. Backend with `stickerSeason` needs to be deployed first since this relies on the new filter.
Since queries to berthProfile are slow, triggering queries from input box too fast seems to cause errors from the backend (the responses will come eventually, but users see error notifications), there's slower debounce rate on input for queries to `berthProfile`. Users will see that UI is loading from the first key press so users won't notice the difference (since the query is slow anyway...).
Also, we need to discuss if the separate stickernumber -only filter is needed, for now the task was to keep both.
VEN-983
https://helsinkisolutionoffice.atlassian.net/browse/VEN-1538

VEN-983 Search by sticker number and season

---

README.md

refs VEN-1558 (noticed "yarn start" didn't work on Windows)
[VEN-1558](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558)
[VEN-1558]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add info how to fix SassError on "yarn start" on Windows

---

src/common/utils/format.ts

formatDate:
- tests using this didn't work on Windows, they returned wrong time
- fixed on Windows also by using process.env.TZ as the timezone in
formatDate function if process.env.TZ is set
refs VEN-1558 (trying to get the tests pass locally on Windows)
[VEN-1558](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558)
[VEN-1558]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: fix formatDate using tests on Windows by using env.TZ as timezone

---

Dockerfile
docker-compose.yml
package.json
setup_user.sh
yarn.lock

Removing graphql dependency in 25b40bf6d421cb76bd2e9a690d7fc37ba91a2907
broke building the Dockerfile. Add back the graphql dependency and
resolve graphql packages to use 15.9.0 in order not to get multiple
installed versions of graphql, which would result in
"yarn types:generate" failing.
Tried resolving graphql to 14.7.0 but that still broke the
"yarn types:generate".
Move the following from devDependencies to dependencies so
"docker compose up --build" and opening the http://localhost:3000/
works:
- @apollo/react-testing
- @testing-library/react
- @testing-library/user-event
Set `tty` and `stdin_open` to `true` in docker-compose.yml in order to
make the "docker compose up --build" not exit right after running
"react-scripts start".
Remove deprecated version number from …

VEN-1577 | fix(docker): use Amazon ECR as source, remove helsinkitest, fix packages

---

src/@types/__generated__/globalTypes.ts
src/common/utils/__tests__/format.test.ts
src/common/utils/__tests__/translations.test.ts
src/common/utils/format.ts
src/common/utils/translations.ts

refs VEN-1575
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEN-1575 | feat: add 14% and 25.5% VAT%, fix formatting non-integer percentages

---

src/features/pricing/__tests__/__snapshots__/Pricing.test.tsx.snap
src/features/pricing/berthPricing/__tests__/__snapshots__/BerthPricing.test.tsx.snap
src/features/pricing/harborServicePricing/__tests__/__snapshots__/HarborServicePricing.test.tsx.snap
src/features/pricing/winterStoragePricing/__tests__/__snapshots__/WinterStoragePricing.test.tsx.snap
src/locales/fi.json

refs VEN-1575
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEN-1575 | fix: change all "alv 24 %" to "alv 25,5 %" in hardcoded translations
