.dockerignore
Dockerfile
docker-compose.yml
package.json
yarn.lock

During development, the Docker image needs to be rebuilt after changes to package.json.
Building the image:
```
docker-compose up --build
```
Running the container:
```
docker-compose up
```

DEVOPS-7 | Docker setup

---

src/common/paragraph/Paragraph.stories.tsx
src/common/paragraph/Paragraph.test.jsx
src/common/paragraph/Paragraph.tsx
src/common/paragraph/__snapshots__/Paragraph.test.jsx.snap
src/common/paragraph/paragraph.module.scss
src/common/title/Title.stories.tsx
src/common/title/Title.tsx
src/common/title/title.module.scss

VEN-248 | Paragraph component

---

src/common/table/Table.stories.tsx

add simple data table to storybook

---

.storybook/addons.js
.storybook/config.js
.storybook/presets.js
package.json
yarn.lock

Refine storybook setup based on this: https://www.learnstorybook.com/design-systems-for-developers/

VEN-287 | Storybook improvements

---

Dockerfile

VEN-313 | Feature/add sentry

---

package.json
src/domain/auth/state/AuthenticationSelectors.ts
src/domain/customers/utils.ts
src/domain/harbors/utils.ts
src/domain/individualHarbor/utils/utils.ts
src/domain/pageHeader/PageHeaderContainer.tsx
src/domain/privateRoute/PrivateRoute.tsx
yarn.lock

Upgrade to typescript 3.7 for optional chaining syntax.

VEN-372 | Feature/typescript 3.7

---

src/common/checkbox/Checkbox.tsx

Checkbox related fix from https://github.com/City-of-Helsinki/berth-reservations-admin/pull/74.

VEN-391 | fix checkbox indeterminate error

---

src/domain/app/App.tsx

Replaces https://github.com/City-of-Helsinki/berth-reservations-admin/pull/67.

VEN-347 | Accept-Language header

---

src/common/spinner/LoadingSpinner.stories.tsx
src/common/spinner/LoadingSpinner.tsx
src/common/spinner/__tests__/LoadingSpinner.test.tsx
src/common/spinner/__tests__/__snapshots__/LoadingSpinner.test.tsx.snap
src/common/spinner/loadingSpinner.module.scss
src/domain/customers/CustomerPageContainer.tsx
src/domain/harbors/HarborsPageContainer.tsx
src/domain/individualCustomer/IndividualCustomerPageContainer.tsx
src/domain/individualHarbor/IndividualHarborPageContainer.tsx
src/locales/fi.json

We discussed having a spinning loader on Friday. I noticed kukkuu-ui has it so I copied it: https://github.com/City-of-Helsinki/kukkuu-ui/tree/develop/src/common/components/spinner.

VEN-407  Add spinning loader

---

package.json
src/assets/styles/_colours.scss
src/index.tsx

https://github.com/City-of-Helsinki/berth-reservations-admin/pull/17
https://github.com/City-of-Helsinki/berth-reservations-admin/pull/41
https://github.com/City-of-Helsinki/berth-reservations-admin/pull/54
https://github.com/City-of-Helsinki/berth-reservations-admin/pull/57

VEN-290 | Feature/use hds colors

---

src/common/grid/grid.module.scss
src/domain/individualHarbor/IndividualHarborPageContainer.tsx
src/domain/individualHarbor/harborProperties/HarborProperties.tsx
src/domain/individualHarbor/harborProperties/harborProperties.module.scss
src/domain/individualHarbor/property/IconOutline.tsx
src/domain/individualHarbor/property/Property.tsx
src/domain/individualHarbor/property/property.module.scss
src/locales/fi.json

VEN-461 | Feature/redefine harbor header

---

src/common/spinner/LoadingSpinner.tsx
src/domain/applications/ApplicationsPageContainer.tsx
src/domain/customers/CustomerPageContainer.tsx
src/domain/harbors/HarborsPageContainer.tsx
src/domain/individualApplication/IndividualApplicationPageContainer.tsx
src/domain/individualCustomer/IndividualCustomerPageContainer.tsx
src/domain/individualHarbor/IndividualHarborPageContainer.tsx
src/domain/offer/OfferPageContainer.tsx

- Shows a loading spinner when data is being fetched.
- Some pages like single harbor page were rendering "no data..." while the data is still being fetched. 
- [VEN-507](https://helsinkisolutionoffice.atlassian.net/browse/VEN-507) Fix "no data" state when the data is still being fetched
- Navigate through the application when going to a page for the first time it should show a loading spinner until the data is being fetched

VEN-507 | Render loading spinner while fetching data

---

src/common/layout/layout.module.scss
src/domain/applications/ApplicationsPageContainer.tsx
src/domain/applications/applicationsPage.module.scss
src/domain/customers/CustomerPageContainer.tsx
src/domain/customers/customersPage.module.scss
src/domain/harbors/HarborsPageContainer.tsx
src/domain/harbors/harborsPage.module.scss
src/domain/individualApplication/IndividualApplicationPageContainer.tsx
src/domain/individualApplication/individualApplicationPage.module.scss
src/domain/individualCustomer/IndividualCustomerPageContainer.tsx
src/domain/individualCustomer/individualCustomerPage/individualCustomerPage.module.scss
src/domain/individualHarbor/individualHarborPage/individualHarborPage.module.scss
src/domain/offer/OfferPageContainer.tsx
src/locales/fi.json

* Use HDS Notification components for no data and error situations
* Move repeated bg gray-50 from page styles to Layout
* PageContainers are not tested right now – but perhaps they should be?

VEN-418 | Frontend: Implement notifications

---

README.md

Pure documentation change. Clarified and corrected parts of the README, fixed issues according to Markdownlint.

Update README, clean up with Markdownlint

---

src/domain/individualApplication/IndividualApplicationPage.tsx
src/locales/fi.json

Added a notification reminding to add a customer to the application
[VEN-545](https://helsinkisolutionoffice.atlassian.net/browse/VEN-545): Frontend: Add a notification on the offer page

VEN-545 | Frontend: Add a notification on the offer page

---

src/domain/individualApplication/IndividualApplicationPage.tsx
src/locales/fi.json

Adjust "application has no customer" notification text
See comments on [VEN-545](https://helsinkisolutionoffice.atlassian.net/browse/VEN-545)

Adjust "application has no customer" notification text

---

.gitlab-ci.yml

Switch to another tunnistamo instance for our staging instance

---

src/domain/offer/__generated__/OFFER_PAGE.ts
src/domain/offer/berthDetails/BerthDetails.stories.tsx
src/domain/offer/berthDetails/BerthDetails.tsx
src/domain/offer/queries.ts
src/domain/offer/utils.ts

Offer page: replace "Asiakas" link with the customer's name & filter leases.
[VEN-561](https://helsinkisolutionoffice.atlassian.net/browse/VEN-561)
* Check Puotilan venesatama [link](http://localhost:3000/offer/QmVydGhBcHBsaWNhdGlvbk5vZGU6MjU2?harbor=40897), pier A, berth 37
* Also check Storybook story for BerthDetails

VEN-561 | Offer page: replace "Asiakas" link with the customer's name & filter leases

---

src/@types/__generated__/globalTypes.ts
src/domain/individualApplication/IndividualApplicationPage.tsx
src/domain/individualApplication/__generated__/FILTERED_CUSTOMERS.ts
src/domain/individualApplication/__generated__/INDIVIDUAL_APPLICATION.ts
src/domain/individualApplication/queries.ts
src/domain/individualApplication/utils.ts
src/locales/fi.json

Update company info fetching logic (company -> organization)
[VEN-557](https://helsinkisolutionoffice.atlassian.net/browse/VEN-557)
No visual changes, merely a data query change. Single application page should work with this.

VEN-557 | Update company info fetching logic

---

src/domain/individualHarbor/__generated__/INDIVIDUAL_HARBOR.ts
src/domain/individualHarbor/queries.ts
src/domain/individualHarbor/utils/utils.ts

Puotilan venesatama → Laituri A → berth 37
Should have 2 past customers.
Aurinkolahden venesatama (Pursilahdenranta) -> berth 3
Should have an active customer.

Correctly query the customer attached to a given lease

---

src/domain/page/Page.tsx
src/domain/page/pageHeader/PageHeader.tsx
src/domain/page/pageHeader/PageHeaderContainer.tsx
src/domain/page/pageHeader/pageHeader.module.scss
src/locales/fi.json

* Add service name to page header
* [VEN-594](https://helsinkisolutionoffice.atlassian.net/browse/VEN-594) | Add service name to page header
* Static feature, ensure that the title looks correct

VEN-594 | Add service name to page header

---

browser-tests/pages/login.ts

- Fix HDS button class (it changed on HDS update)
Run browser tests: `yarn browser-test` they should pass.
🤣

Fix browser tests login button class

---

browser-tests/pages/harbors.ts

Fix browser tests harbor page class

Fix browser tests harbor page class

---

package.json
yarn.lock

Add missing apollo-link-context dependency.
https://helsinkisolutionoffice.atlassian.net/browse/VEN-701

VEN-701 | Fix docker build

---

src/features/winterStorageAreaList/WinterStorageAreaList.tsx
src/features/winterStorageAreaList/__tests__/__snapshots__/WinterStorageAreaList.test.tsx.snap

* Add global filter to WinterStorageAreaList
* [VEN-716](https://helsinkisolutionoffice.atlassian.net/browse/VEN-716): FE - Winter storage areas page: Global filter
* Updated WinterStorageAreaList test snapshot
* Test that the filter works as expected

VEN-716 | Add global filter to WinterStorageAreaList

---

src/features/harborList/HarborList.tsx
src/features/harborList/__tests__/utils.test.ts
src/features/harborList/berthSummary/BerthSummary.tsx
src/features/harborList/berthSummary/berthSummary.module.scss
src/features/harborList/utils.ts
src/locales/fi.json

* Add a berth summary section to harbor list
* [VEN-228](https://helsinkisolutionoffice.atlassian.net/browse/VEN-228): Implement Summary section
* Added tests for new calculation utility
* Check that the new component is visible and looks as expected

VEN-228 | Add a berth summary section to harbor list

---

.gitlab-ci.yml

Fix building for release

---

src/features/customerList/tableTools/CustomerListTableTools.tsx
src/features/customerMessageForm/CustomerMessageForm.tsx
src/features/customerMessageForm/CustomerMessageFormContainer.tsx
src/features/customerMessageForm/__tests__/CustomerMessageForm.test.tsx
src/features/customerMessageForm/__tests__/CustomerMessageFormContainer.test.tsx
src/features/customerMessageForm/__tests__/__snapshots__/CustomerMessageForm.test.tsx.snap
src/features/customerMessageForm/__tests__/__snapshots__/CustomerMessageFormContainer.test.tsx.snap
src/features/customerMessageForm/customerMessageForm.module.scss
src/features/customerMessageForm/preview/Preview.tsx
src/features/customerMessageForm/preview/__tests__/Preview.test.tsx
src/features/customerMessageForm/preview/__tests__/__snapshots__/Preview.test.tsx.snap
src/features/customerMessageForm/preview/preview.module.scss
src/locales/fi.json

* Move message preview inside form modal, add recipient count 
* [VEN-646](https://helsinkisolutionoffice.atlassian.net/browse/VEN-646): FE - Customers page: Preview for sending messages modal
* Updated automated tests
* The message form should now match the designs in Abstract

VEN-646 | Preview for sending messages modal

---

.gitlab-ci.yml

Update BE address for prod
[VEN-706](https://helsinkisolutionoffice.atlassian.net/browse/VEN-706)
After merging and releasing should fetch data from updated endpoint.

VEN-706 | Update BE address for prod

---

browser-tests/navigateAndView.ts

Make WS and harbors browser test a bit more lenient of data

Fix browser tests

---

browser-tests/customerListView.ts
browser-tests/pages/customers.ts

Fix customer list test

---

.gitlab-ci.yml

Revert "Use temporarily direct BE URL".

Revert "Use temporarily direct BE URL"

---

src/@types/__generated__/globalTypes.ts
src/features/unmarkedWsNoticeList/__fixtures__/mockData.ts
src/features/unmarkedWsNoticeList/__generated__/UNMARKED_WINTER_STORAGE_NOTICES.ts
src/features/unmarkedWsNoticeList/queries.ts
src/features/winterStorageApplicationList/__fixtures__/mockData.ts
src/features/winterStorageApplicationList/__generated__/WINTER_STORAGE_APPLICATIONS.ts
src/features/winterStorageApplicationList/queries.ts

* Filter WS applications for marked and unmarked areas
* [VEN-844](https://helsinkisolutionoffice.atlassian.net/browse/VEN-844): FE - Filter WS applications for marked and unmarked areas
* Updated mockData
* "Talvisäilytyshakemukset" and "Nostojärjestysilmoitukset" should have different contents

VEN-844 | Filter WS applications for marked and unmarked areas

---

src/common/hooks/__fixtures__/useCreateNewCustomerMockData.ts
src/common/hooks/useCreateNewCustomer.ts
src/common/mutations/__generated__/CREATE_NEW_PROFILE.ts
src/common/mutations/createProfile.ts
src/features/applicationView/ApplicationViewContainer.tsx
src/features/customerForm/AddCustomerFormContainer.tsx
src/features/customerForm/EditCustomerFormContainer.tsx
src/features/customerForm/__tests__/EditCustomerFormContainer.test.tsx
src/features/customerForm/__tests__/__snapshots__/EditCustomerFormContainer.test.tsx.snap
src/features/customerList/CustomerListContainer.tsx
src/features/customerList/tableTools/CustomerListTableTools.tsx
src/features/customerList/tableTools/__tests__/__snapshots__/CustomerListTableTools.test.tsx.snap
src/features/customerList/tableTools/customerListTableTools.module.scss
src/features/customerList/utils.ts
src/features/customerView/CustomerViewContainer.tsx
src/features/unmarkedWsNoticeView/UnmarkedWsNoticeViewContainer.tsx
src/features/winterStorageApplicationView/WinterStorageApplicationViewContainer.tsx
src/locales/fi.json

* Customer list: Add new customer
* Customer list: Show name and municipality from organization data
* [VEN-773](https://helsinkisolutionoffice.atlassian.net/browse/VEN-773): FE - Customer list: Add new customer 
* Navigate to customer list
* Add a private customer
* Add an organization customer

VEN-773 | Customer list: Add new customer

---

browser-tests/pages/customers.ts

Fix browser tests selector for deselectAll.

Fix browser tests selector for deselectAll

---

src/app/__tests__/apolloClient.test.ts
src/app/apolloClient.ts

* Added tests for apolloClient errorHandler
* New tests

Add tests for apolloClient errorHandler

---

.gitlab-ci.yml
.travis.yml

VEN-978 | Switch to GH flow

---

.gitlab-ci.yml

VEN-978 | Fix build triggers

---

src/features/unmarkedWsNoticeList/UnmarkedWsNoticeList.tsx
src/features/unmarkedWsNoticeList/printAllStickersButton/PrintAllStickersButton.tsx
src/features/unmarkedWsNoticeList/printAllStickersButton/__generated__/UNMARKED_WINTER_STORAGE_NOTICES_STICKERS.ts
src/features/unmarkedWsNoticeList/printAllStickersButton/printAllStickersButton.module.scss
src/features/unmarkedWsNoticeList/printAllStickersButton/queries.ts
src/features/unmarkedWsNoticeList/utils.ts
src/locales/fi.json

Additionally prints the mails in ascending sticker number order.

Add option to print all stickers

---

src/@types/__generated__/globalTypes.ts
src/common/utils/translations.ts
src/features/customerView/invoicingHistoryCard/InvoicingHistoryCard.tsx
src/locales/fi.json

- Add an error badge for orderStatus

Add an error badge for orderStatus

---

src/features/harborView/__fixtures__/mockData.ts
src/features/harborView/__generated__/INDIVIDUAL_HARBOR.ts
src/features/harborView/forms/pierForm/PierCreateForm.tsx
src/features/harborView/forms/pierForm/PierForm.tsx
src/features/harborView/forms/pierForm/__generated__/PIER_AND_BOAT_TYPES.ts
src/features/harborView/forms/pierForm/__tests__/PierForm.test.tsx
src/features/harborView/forms/pierForm/__tests__/__snapshots__/PierForm.test.tsx.snap
src/features/harborView/forms/pierForm/pierForm.module.scss
src/features/harborView/forms/pierForm/queries.ts
src/features/harborView/forms/pierForm/utils/utils.ts
src/features/harborView/forms/types.ts
src/features/harborView/pierSelectHeader/pierProperties/PierProperties.tsx
src/features/harborView/queries.ts
src/features/harborView/types.ts
src/features/harborView/utils.ts
src/locales/fi.json

* Add pier price category display and input
* [VEN-1026](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1026): FE - Set pricing tier for pier

VEN-1026 | Add pier price category display and input

---

src/features/linkApplicationToCustomer/LinkApplicationToCustomerContainer.tsx

* Make createNewCustomer refetch customer list in LinkApplicationToCustomer
* [VEN-1029](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1029): 'Create customer' button doesn’t do anything until page is refreshed

VEN-1029 | Make createNewCustomer refetch customer list in LinkApplicationToCustomer

---

src/common/utils/featureFlags.ts
src/features/customerView/invoicingHistoryCard/InvoicingHistoryCard.tsx

* Remove additional invoice feature flag
* [VEN-1041](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1041): Remove additional invoice feature flag

VEN-1041 | Remove additional invoice feature flag

---

.github/workflows/browser-tests.yml
browser-tests/customerListView.ts
browser-tests/navigateAndView.ts
browser-tests/pages/pricing.ts

- Add a step for uploading failed screenshots as GH artifacts
- Fix the customers' list browser tests
- Update the pricing page browser tests
[**VEN-1056**](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1056): Fix browser tests for Admin UI

VEN-1056 | Upload screenshots of failed browser tests

---

src/@types/__generated__/globalTypes.ts
src/features/applicationList/__generated__/BERTH_APPLICATIONS.ts
src/features/applicationView/__generated__/INDIVIDUAL_APPLICATION.ts
src/features/customerView/__generated__/INDIVIDUAL_CUSTOMER.ts
src/features/offer/__generated__/OFFER.ts
src/features/pricing/Pricing.tsx
src/features/pricing/PricingContainer.tsx
src/features/pricing/additionalServicePricing/AdditionalServicePricing.tsx
src/features/pricing/additionalServicePricing/__generated__/ADD_ADDITIONAL_SERVICE_PRICE.ts
src/features/pricing/additionalServicePricing/__generated__/DELETE_ADDITIONAL_SERVICE_PRICE.ts
src/features/pricing/additionalServicePricing/__tests__/AdditionalServicePricing.test.tsx
src/features/pricing/additionalServicePricing/form/AdditionalServicesForm.tsx
src/features/pricing/additionalServicePricing/form/__tests__/__snapshots__/AdditionalServicesForm.test.tsx.snap
src/features/pricing/additionalServicePricing/mutations.ts
src/features/unmarkedWsNoticeList/__generated__/UNMARKED_WINTER_STORAGE_NOTICES.ts
src/features/unmarkedWsNoticeView/__generated__/UNMARKED_WINTER_STORAGE_NOTICE.ts
src/features/winterStorageApplicationList/__generated__/WINTER_STORAGE_APPLICATIONS.ts
src/features/winterStorageApplicationView/__generated__/INDIVIDUAL_WINTER_STORAGE_APPLICATION.ts
src/locales/fi.json

* Add 'delete additional service'
* Show loading after add/edit/update additional service price
* [VEN-1030](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1030): Add 'delete additional service'
* Updated existing tests, no new tests
* Deleting an additional service price should be possible

VEN-1030 | Add 'delete additional service'

---

.testcaferc.json

* Increase testcafe assertion timeout to 5000 ms

Increase testcafe assertion timeout to 5000 ms

---

.env
.github/workflows/review.yml
.github/workflows/staging.yml
src/features/auth/__snapshots__/authService.test.js.snap

Starts to use KuVa Tunnistamo in review and staging to allow testing of review envs with authentication.
DEVOPS-237
Sign in to admin at review env.

KuVa Tunnistamo to review and staging

---

.github/workflows/production.yml

Add additional hostnames block for prod deployment

---

.testcaferc.json
browser-tests/utils/login.ts

* Increase browser test timeout to 10000ms

Increase browser test timeout to 10000ms

---

src/common/dataSummary/dataSummary.module.scss
src/common/layout/Layout.tsx
src/common/layout/layout.module.scss
src/features/errorPage/__tests__/__snapshots__/ErrorPage.test.tsx.snap
src/features/recurringInvoices/RecurringInvoices.tsx
src/features/recurringInvoices/RecurringInvoicesContainer.tsx
src/features/recurringInvoices/__generated__/RECURRING_INVOICES.ts
src/features/recurringInvoices/queries.ts
src/features/recurringInvoices/recurringInvoices.module.scss
src/features/recurringInvoices/utils.ts
src/locales/fi.json

* Fix statistics and info text in 'Kausilaskut' view
* [VEN-1139](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1139): Fix statistics and info text in 'Kausilaskut' view
* _None_
* The new statistics ad info text should match the description on the ticket
* Not enough data in staging to confirm

VEN-1139 | Fix statistics and info text in 'Kausilaskut' view

---

src/@types/__generated__/globalTypes.ts
src/features/customerView/CustomerView.tsx
src/features/customerView/CustomerViewContainer.tsx
src/features/customerView/__generated__/CANCEL_BERTH_LEASE.ts
src/features/customerView/__generated__/CANCEL_WINTER_STORAGE_LEASE.ts
src/features/customerView/leasesCard/BerthLeasesCard.tsx
src/features/customerView/leasesCard/LeasesCard.test.tsx
src/features/customerView/leasesCard/LeasesCard.tsx
src/features/customerView/leasesCard/WinterStorageLeasesCard.tsx
src/features/customerView/leasesCard/__snapshots__/LeasesCard.test.tsx.snap
src/features/customerView/mutations.ts
src/locales/fi.json

* Terminate leases from customerView
* [VEN-936](https://helsinkisolutionoffice.atlassian.net/browse/VEN-936): FE - Implement terminate leases
* Updated snapshots
* Terminating a lease from the customer view should be possible. You could try with Kalle's berths

VEN-936 | Terminate leases from customerView

---

src/features/applicationView/berthOfferCard/__tests__/__snapshots__/BerthOfferCard.test.tsx.snap
src/features/invoiceCard/InvoiceCardContainer.tsx
src/features/invoiceCard/invoiceActions/InvoiceActions.tsx

- Hide invoice action based on the order status
[VEN-1257](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1257)

VEN-1257 | Make offer action permissions more granular

---

package.json

* Temporarily disable browser tests on CI

Temporarily disable browser tests on CI

---

src/features/berthOffer/utils.ts

- Convert defined boat dimensions to numbers

VEN-1190 | Convert defined boat dimensions to numbers

---

src/@types/__generated__/globalTypes.ts
src/features/applicationView/ApplicationView.tsx
src/features/applicationView/__generated__/INDIVIDUAL_APPLICATION.ts
src/features/applicationView/berthSwitchOfferCard/BerthSwitchOfferCard.tsx
src/features/applicationView/berthSwitchOfferCard/BerthSwitchOfferCardContainer.tsx
src/features/applicationView/berthSwitchOfferCard/__generated__/UPDATE_BERTH_SWITCH_OFFER.ts
src/features/applicationView/berthSwitchOfferCard/berthSwitchOfferCard.module.scss
src/features/applicationView/berthSwitchOfferCard/mutations.ts
src/features/applicationView/berthSwitchOfferCard/types.ts
src/features/applicationView/berthSwitchOfferCard/utils.ts
src/features/applicationView/queries.ts
src/locales/fi.json

* Cancel berth switch offers
* Show switch offer number
* Split BerthSwitchOfferCard to container and presentational components
* [VEN-1209](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1209): Cancel a switch offer
* Cancelling a switch offer should work

VEN-1209 | Cancel a switch offer

---

package.json

- Bump up version number to 2.0.2

Bump up version number to 2.0.2

---

package.json
src/features/unmarkedWsNoticeList/utils.ts

- Small adjustments for Stickers text

VEN-1374 | Adjustments for Stickers Text

---

src/app/apolloClient.ts

VEN-1468 VEN-1470. Save profile-query's OBJECT_DOES_NOT_EXIST_ERROR from a toaster. The missing profiles are already informed other ways and it does not make sense to pop up an error notification multiple times a page load.
Names are already formatted:

Ignore profile queries' does not exist errors from a toaster

---

README.md

This PR adds instructions for setting up the whole stack locally.

Add instruction for running all services locally

---

src/@types/__generated__/globalTypes.ts
src/common/winterStorageAreaCard/WinterStorageAreaCard.tsx
src/features/winterStorageAreaView/WinterStorageAreaView.tsx
src/features/winterStorageAreaView/WinterStorageAreaViewContainer.tsx
src/features/winterStorageAreaView/__fixtures__/mockData.ts
src/features/winterStorageAreaView/__generated__/INDIVIDUAL_WINTER_STORAGE_AREA.ts
src/features/winterStorageAreaView/__tests__/__snapshots__/WinterStorageAreaViewContainer.test.tsx.snap
src/features/winterStorageAreaView/forms/WinterStorageAreaEditForm.tsx
src/features/winterStorageAreaView/forms/__generated__/UPDATE_WINTER_STORAGE_AREA.ts
src/features/winterStorageAreaView/forms/__generated__/WINTER_STORAGE_AREA_FORM.ts
src/features/winterStorageAreaView/forms/mutations.ts
src/features/winterStorageAreaView/forms/queries.ts
src/features/winterStorageAreaView/forms/types.ts
src/features/winterStorageAreaView/forms/utils/utils.ts
src/features/winterStorageAreaView/forms/winterStorageAreaEditForm.module.scss
src/features/winterStorageAreaView/queries.ts
src/locales/fi.json

Adds the edit form and edit button to the individual winter storage area

VEN-1340: Winter storage area edit

---

src/features/winterStorageAreaView/forms/placeForm/PlaceCreateForm.tsx
src/features/winterStorageAreaView/forms/placeForm/PlaceEditForm.tsx
src/features/winterStorageAreaView/forms/placeForm/PlaceForm.tsx
src/features/winterStorageAreaView/forms/placeForm/__generated__/INDIVIDUAL_PLACE.ts
src/features/winterStorageAreaView/forms/placeForm/__tests__/__snapshots__/PlaceEditForm.test.tsx.snap
src/features/winterStorageAreaView/forms/placeForm/__tests__/__snapshots__/PlaceForm.test.tsx.snap
src/features/winterStorageAreaView/forms/placeForm/queries.ts
src/features/winterStorageAreaView/forms/types.ts
src/features/winterStorageAreaView/forms/utils/utils.ts
src/features/winterStoragePlaceDetails/WinterStoragePlaceDetails.tsx
src/features/winterStoragePlaceDetails/WinterStoragePlaceDetailsContainer.tsx
src/features/winterStoragePlaceDetails/__generated__/WINTER_STORAGE_PLACE_DETAILS.ts
src/features/winterStoragePlaceDetails/queries.ts

Adds comments field to the Place forms and also to the details view.

VEN-1515: Add comment field to Place create/edit/view

---

.prod/nginx.conf
Dockerfile
package.json
yarn.lock

Openshift write permission DEVOPS-481

---

Dockerfile
README.md
package.json
yarn.lock

VEN-1553
- Update the node types package
- Update the docker base image

Upgrade the Node version to 14

---

package.json
tsconfig.json
yarn.lock

Update the apollo

---

src/features/unmarkedWsNoticeList/utils.ts

refs VEN-1558
Co-authored-by: Kari Salminen <kari.salminen@anders.com>
Co-authored-by: Jarkko Luukkonen <jarkko.luukkonen@hel.fi>
[VEN-1558](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558)
[VEN-1558]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VEN-1558 | feat: update sticker PDF content (i.e. päivitä tarrakirjeiden sisältö)

---

src/features/customerList/__fixtures__/mockData.ts
src/features/customerList/__generated__/CUSTOMERS.ts
src/features/customerList/__mocks__/customersMockResponse.ts
src/features/customerList/queries.ts

fix: remove image field from profile gql queries

---

src/features/auth/authService.ts

fix: set logout redirect url to root
